# RAG-Powered Document Assistant

## 2.1 Load & Inspect

This notebook implements a Retrieval-Augmented Generation (RAG) system
for question answering over the complete Sherlock Holmes canon by
Arthur Conan Doyle.

The RAG pipeline includes:

1. Document preparation and inspection
2. Text extraction
3. Chunking
4. Embedding generation
5. Vector storage
6. Retrieval
7. Prompt construction
8. Answer generation
9. Evaluation
10. Exporting the vector store and configuration

In [4]:
import sys
print(sys.executable)

C:\Users\New\OneDrive - Faculty Of Science (Ain Shams University)\RAG_Assistant_Project\.venv\Scripts\python.exe

In [5]:
from pathlib import Path
from pypdf import PdfReader

# Project root directory
PROJECT_ROOT = Path.cwd().parent

# Source PDF
PDF_PATH = PROJECT_ROOT / "data" / "cano.pdf"

print("Project root:", PROJECT_ROOT)
print("PDF path:", PDF_PATH)
print("PDF exists:", PDF_PATH.exists())
print("PDF size (MB):", round(PDF_PATH.stat().st_size / (1024 * 1024), 2))

Project root: C:\Users\New\OneDrive - Faculty Of Science (Ain Shams University)\RAG_Assistant_Project
PDF path: C:\Users\New\OneDrive - Faculty Of Science (Ain Shams University)\RAG_Assistant_Project\data\cano.pdf
PDF exists: True
PDF size (MB): 4.82

In [6]:
reader = PdfReader(PDF_PATH)

num_pages = len(reader.pages)

print("Number of pages:", num_pages)

Number of pages: 987

In [8]:
pages = []
failed_pages = []

for page_number, page in enumerate(reader.pages, start=1):
    try:
        text = page.extract_text()

        if text and text.strip():
            pages.append({
                "page_number": page_number,
                "text": text.strip()
            })
        else:
            failed_pages.append(page_number)

    except Exception as e:
        failed_pages.append(page_number)
        print(f"Failed to parse page {page_number}: {e}")

print("Total PDF pages:", num_pages)
print("Pages with extracted text:", len(pages))
print("Pages without usable text:", len(failed_pages))

Total PDF pages: 987
Pages with extracted text: 883
Pages without usable text: 104

In [9]:
print("First extracted page:")
print(pages[0]["text"][:2000])

print("\n" + "=" * 80)

print("Last extracted page:")
print(pages[-1]["text"][:2000])

First extracted page:
The Complete Sherlock Holmes
Arthur Conan Doyle

================================================================================
Last extracted page:
The Adventure of the Retired Colourman
“Write a message.”
“Exactly. You would like to tell people how you
died. No use writing on paper. That would be seen.
If you wrote on the wall someone might rest upon it.
Now, look here! Just above the skirting is scribbled
with a purple indelible pencil: ‘We we—’ That’s all.”
“What do you make of that?”
“Well, it’s only a foot above the ground. The poor
devil was on the ﬂoor dying when he wrote it. He
lost his senses before he could ﬁnish.”
“He was writing, ‘We were murdered.’ ”
“That’s how I read it. If you ﬁnd an indelible
pencil on the body—”
“We’ll look out for it, you may be sure. But those
securities? Clearly there was no robbery at all. And
yet he did possess those bonds. We veriﬁed that.”
“You may be sure he has them hidden in a safe
place. When the whole elopement had passed into
history, he would suddenly discover them and an-
nounce that the guilty couple had relented and sent
back the plunder or had dropped it on the way.”
“You certainly seem to have met every difﬁculty,”
said the inspector. “Of course, he was bound to call
us in, but why he should have gone to you I can’t
understand.”
“Pure swank!” Holmes answered. “He felt so
clever and so sure of himself that he imagined no
one could touch him. He could say to any suspi-
cious neighbour, ‘Look at the steps I have taken. I
have consulted not only the police but even Sherlock
Holmes.’ ”
The inspector laughed.
“We must forgive you your ‘even,’ Mr. Holmes,”
said he, “it’s as workmanlike a job as I can remember.”
A couple of days later my friend tossed across to
me a copy of the bi-weekly North Surrey Observer. Un-
der a series of ﬂaming headlines, which began with
“The Haven Horror” and ended with “Brilliant Police
Investigation,” there was a packed column of print
which gave the ﬁrst consecutive account of the affair.
The concluding paragraph is typical of the whole. It
ran thus:
The remarkable acumen by which Inspector
MacKinnon deduced from the smell of paint
tha

In [10]:
print("First 20 pages without usable text:")
print(failed_pages[:20])

First 20 pages without usable text:
[6, 8, 10, 12, 40, 42, 70, 72, 124, 126, 128, 140, 142, 154, 156, 166, 178, 180, 190, 192]

In [11]:
page_lengths = [len(page["text"]) for page in pages]

print("Total extracted characters:", sum(page_lengths))
print("Average characters per page:", round(sum(page_lengths) / len(page_lengths)))
print("Shortest extracted page:", min(page_lengths))
print("Longest extracted page:", max(page_lengths))

Total extracted characters: 3584289
Average characters per page: 4059
Shortest extracted page: 12
Longest extracted page: 5415

In [12]:
import pandas as pd

pages_df = pd.DataFrame(pages)

pages_df.head()

   page_number                                               text
0            1   The Complete Sherlock Holmes\nArthur Conan Doyle
1            2  This text is provided to you “as-is” without a...
2            3  T able of contents\nA Study In Scarlet . . . ....
3            4  The Return of Sherlock Holmes\nThe Adventure o...
4            5  The Case-Book of Sherlock Holmes\nPreface . . ...

### Text Extraction Findings

The PDF contains 987 pages in total. Text extraction was successful for
883 pages, while 104 pages did not contain usable extracted text.

A total of 3,584,289 characters were extracted, with an average of
approximately 4,059 characters per extracted page.

The extracted text was manually inspected on the first and last
available pages and was found to contain readable book content.

The pages without usable text may correspond to illustrations,
blank/formatting pages, or pages whose content is not represented as
extractable text. Since this project focuses on text-based question
answering, the extracted textual content will be used as the main RAG
corpus.

## 2.2 Chunking Strategy

The extracted pages are divided into smaller overlapping text chunks
to improve retrieval quality.

A Recursive Character Text Splitter is used because it attempts to
split text at natural boundaries such as paragraphs and sentences
before falling back to smaller separators.

Configuration:

- Chunk size: 1000 characters
- Chunk overlap: 150 characters

The overlap helps preserve context when an important sentence or piece
of information lies near a chunk boundary.

In [13]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=150,
    separators=["\n\n", "\n", ". ", " ", ""]
)

In [14]:
chunks = []

for page in pages:
    page_chunks = text_splitter.split_text(page["text"])

    for chunk_index, chunk_text in enumerate(page_chunks):
        chunks.append({
            "text": chunk_text,
            "page_number": page["page_number"],
            "chunk_index": chunk_index,
            "source": "The Complete Sherlock Holmes"
        })

print("Total chunks:", len(chunks))

Total chunks: 4519

In [15]:
print("First chunk:")
print(chunks[0]["text"])

print("\n" + "=" * 80)

print("First chunk metadata:")
print({
    "page_number": chunks[0]["page_number"],
    "chunk_index": chunks[0]["chunk_index"],
    "source": chunks[0]["source"]
})

First chunk:
The Complete Sherlock Holmes
Arthur Conan Doyle

================================================================================
First chunk metadata:
{'page_number': 1, 'chunk_index': 0, 'source': 'The Complete Sherlock Holmes'}

In [16]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedding model loaded successfully.")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\New\OneDrive - Faculty Of Science (Ain Shams University)\RAG_Assistant_Project\.venv\Lib\site-packages\huggingface_hub\file_download.py:142: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\New\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding model loaded successfully.

In [17]:
texts = [chunk["text"] for chunk in chunks]

embeddings = embedding_model.encode(
    texts,
    show_progress_bar=True
)

print("Number of embeddings:", len(embeddings))
print("Embedding dimension:", embeddings.shape[1])

Batches:   0%|          | 0/142 [00:00<?, ?it/s]

Number of embeddings: 4519
Embedding dimension: 384

In [18]:
import chromadb
from pathlib import Path

# Directory where the vector database will be persisted
VECTOR_STORE_PATH = PROJECT_ROOT / "data" / "vector_store"

VECTOR_STORE_PATH.mkdir(parents=True, exist_ok=True)

# Create persistent Chroma client
chroma_client = chromadb.PersistentClient(
    path=str(VECTOR_STORE_PATH)
)

# Create collection
collection = chroma_client.get_or_create_collection(
    name="sherlock_holmes"
)

print("Vector store path:", VECTOR_STORE_PATH)
print("Collection name:", collection.name)

Vector store path: C:\Users\New\OneDrive - Faculty Of Science (Ain Shams University)\RAG_Assistant_Project\data\vector_store
Collection name: sherlock_holmes

In [19]:
batch_size = 500

for start in range(0, len(chunks), batch_size):
    end = min(start + batch_size, len(chunks))

    batch_chunks = chunks[start:end]
    batch_embeddings = embeddings[start:end]

    collection.add(
        ids=[f"chunk_{i}" for i in range(start, end)],
        documents=[chunk["text"] for chunk in batch_chunks],
        embeddings=batch_embeddings.tolist(),
        metadatas=[
            {
                "source": chunk["source"],
                "page_number": chunk["page_number"],
                "chunk_index": chunk["chunk_index"]
            }
            for chunk in batch_chunks
        ]
    )

    print(f"Stored chunks {start} → {end - 1}")

print("\nTotal documents in Chroma:", collection.count())

Stored chunks 0 → 499
Stored chunks 500 → 999
Stored chunks 1000 → 1499
Stored chunks 1500 → 1999
Stored chunks 2000 → 2499
Stored chunks 2500 → 2999
Stored chunks 3000 → 3499
Stored chunks 3500 → 3999
Stored chunks 4000 → 4499
Stored chunks 4500 → 4518

Total documents in Chroma: 4519

## 2.4 Retrieval & Prompting

The retrieval stage searches the Chroma vector store for the most
semantically relevant chunks to a user question.

The question is embedded using the same embedding model used for the
document chunks. Chroma then retrieves the nearest chunks based on
vector similarity.

In [20]:
def retrieve_documents(query, top_k=5):
    query_embedding = embedding_model.encode([query])

    results = collection.query(
        query_embeddings=query_embedding.tolist(),
        n_results=top_k
    )

    retrieved_chunks = []

    for i in range(len(results["documents"][0])):
        retrieved_chunks.append({
            "text": results["documents"][0][i],
            "page_number": results["metadatas"][0][i]["page_number"],
            "chunk_index": results["metadatas"][0][i]["chunk_index"],
            "source": results["metadatas"][0][i]["source"],
            "distance": results["distances"][0][i]
        })

    return retrieved_chunks

In [21]:
query = "Who is Dr. Watson?"

retrieved = retrieve_documents(query, top_k=5)

for i, result in enumerate(retrieved, start=1):
    print(f"\n--- Retrieved Chunk {i} ---")
    print("Page:", result["page_number"])
    print("Distance:", round(result["distance"], 4))
    print(result["text"][:1000])

--- Retrieved Chunk 1 ---
Page: 940
Distance: 0.8233
“As you like, Mr. Holmes. You will, I am sure,
understand my having some reserves in the matter.”
“You will appreciate it, Watson, when I tell you
that this gentleman, Mr. Trevor Bennett, is profes-
sional assistant to the great scientist, lives under his
roof, and is engaged to his only daughter. Certainly
we must agree that the professor has every claim upon
his loyalty and devotion. But it may best be shown
by taking the necessary steps to clear up this strange
mystery.”
“I hope so, Mr. Holmes. That is my one object.
Does Dr. Watson know the situation?”
“I have not had time to explain it.”
“Then perhaps I had better go over the ground
again before explaining some fresh developments.”
“I will do so myself,” said Holmes, “in order to
show that I have the events in their due order. The
professor, Watson, is a man of European reputation.
His life has been academic. There has never been a
breath of scandal. He is a widower with one daugh-

--- Retrieved Chunk 2 ---
Page: 809
Distance: 0.8585
I am going for a doctor this very hour,’ said I. ‘Let it
be Watson, then,’ said he. I wouldn’t waste an hour
in coming to him, sir, or you may not see him alive.”
I was horriﬁed for I had heard nothing of his ill-
ness. I need not say that I rushed for my coat and my
hat. As we drove back I asked for the details.
“There is little I can tell you, sir. He has been work-
ing at a case down at Rotherhithe, in an alley near the
river, and he has brought this illness back with him.
He took to his bed on Wednesday afternoon and has
never moved since. For these three days neither food
nor drink has passed his lips.”
“Good God! Why did you not call in a doctor?”
“He wouldn’t have it, sir. You know how mas-
terful he is. I didn’t dare to disobey him. But he’s
not long for this world, as you’ll see for yourself the
moment that you set eyes on him.”
He was indeed a deplorable spectacle. In the dim
light of a foggy November day the sick room was a

--- Retrieved Chunk 3 ---
Page: 33
Distance: 0.8726
slapped his thigh in a paroxysm of amusement.
“The fun of it is,” he cried, “that that fool Lestrade,
who thinks himself so smart, has gone off upon the
wrong track altogether. He is after the secretary
Stangerson, who had no more to do with the crime
than the babe unborn. I have no doubt that he has
caught him by this time.”
The idea tickled Gregson so much that he laughed
until he choked.
“And how did you get your clue?”
“Ah, I’ll tell you all about it. Of course, Doctor
Watson, this is strictly between ourselves. The ﬁrst dif-
ﬁculty which we had to contend with was the ﬁnding
of this American’s antecedents. Some people would
have waited until their advertisements were answered,
or until parties came forward and volunteered infor-
mation. That is not Tobias Gregson’s way of going to
work. You remember the hat beside the dead man?”
“Yes,” said Holmes; “by John Underwood and
Sons, 129, Camberwell Road.”
Gregson looked quite crest-fallen.

--- Retrieved Chunk 4 ---
Page: 77
Distance: 0.8879
to do, Miss Morstan?”
“That is exactly what I want to ask you.”
“Then we shall most certainly go. You and I
and—yes, why, Dr. Watson is the very man. Your cor-
respondent says two friends. He and I have worked
together before.”
“But would he come?” she asked, with something
appealing in her voice and expression.
“I should be proud and happy,” said I, fervently,
“if I can be of any service.”
“You are both very kind,” she answered. “I have
led a retired life, and have no friends whom I could
appeal to. If I am here at six it will do, I suppose?”
71

--- Retrieved Chunk 5 ---
Page: 143
Distance: 0.8914
glance from his small fat-encircled eyes.
“Try the settee,” said Holmes, relapsing into his
armchair and putting his ﬁngertips together, as was
his custom when in judicial moods. “I know, my dear
Watson, that you share my love of all that is bizarre
and outside the conventions and humdrum routine
of everyday life. You have shown your relish for it by
the enthusiasm which has prompted you to chronicle,
and, if you will excuse my saying so, somewhat to
embellish so many of my own little adventures.”
“Your cases have indeed been of the greatest inter-
est to me,” I observed.
“You will remember that I remarked the other day,
just before we went into the very simple problem
presented by Miss Mary Sutherland, that for strange
effects and extraordinary combinations we must go
to life itself, which is always far more daring than any
effort of the imagination.”
“A proposition which I took the liberty of doubt-
ing.”
“You did, Doctor, but none the less you must come

### Prompt Construction

The retrieved chunks are combined with the user's question to create
a grounded prompt for the language model.

The model is instructed to answer using the provided context and to
avoid introducing information that is not supported by the retrieved
content.

In [22]:
def build_prompt(question, retrieved_chunks):
    context_parts = []

    for i, chunk in enumerate(retrieved_chunks, start=1):
        context_parts.append(
            f"[Source {i} | Page {chunk['page_number']}]\n"
            f"{chunk['text']}"
        )

    context = "\n\n".join(context_parts)

    prompt = f"""You are a question-answering assistant for The Complete Sherlock Holmes.

Answer the user's question using only the provided context.

If the answer cannot be determined from the context, say:
"I could not find enough information in the provided context."

Always mention the relevant source page(s) in your answer.

Context:
{context}

Question:
{question}

Answer:
"""

    return prompt

In [23]:
question = "Who is Dr. Watson?"

prompt = build_prompt(question, retrieved)

print(prompt[:5000])

You are a question-answering assistant for The Complete Sherlock Holmes.

Answer the user's question using only the provided context.

If the answer cannot be determined from the context, say:
"I could not find enough information in the provided context."

Always mention the relevant source page(s) in your answer.

Context:
[Source 1 | Page 940]
“As you like, Mr. Holmes. You will, I am sure,
understand my having some reserves in the matter.”
“You will appreciate it, Watson, when I tell you
that this gentleman, Mr. Trevor Bennett, is profes-
sional assistant to the great scientist, lives under his
roof, and is engaged to his only daughter. Certainly
we must agree that the professor has every claim upon
his loyalty and devotion. But it may best be shown
by taking the necessary steps to clear up this strange
mystery.”
“I hope so, Mr. Holmes. That is my one object.
Does Dr. Watson know the situation?”
“I have not had time to explain it.”
“Then perhaps I had better go over the ground
again before explaining some fresh developments.”
“I will do so myself,” said Holmes, “in order to
show that I have the events in their due order. The
professor, Watson, is a man of European reputation.
His life has been academic. There has never been a
breath of scandal. He is a widower with one daugh-

[Source 2 | Page 809]
I am going for a doctor this very hour,’ said I. ‘Let it
be Watson, then,’ said he. I wouldn’t waste an hour
in coming to him, sir, or you may not see him alive.”
I was horriﬁed for I had heard nothing of his ill-
ness. I need not say that I rushed for my coat and my
hat. As we drove back I asked for the details.
“There is little I can tell you, sir. He has been work-
ing at a case down at Rotherhithe, in an alley near the
river, and he has brought this illness back with him.
He took to his bed on Wednesday afternoon and has
never moved since. For these three days neither food
nor drink has passed his lips.”
“Good God! Why did you not call in a doctor?”
“He wouldn’t have it, sir. You know how mas-
terful he is. I didn’t dare to disobey him. But he’s
not long for this world, as you’ll see for yourself the
moment that you set eyes on him.”
He was indeed a deplorable spectacle. In the dim
light of a foggy November day the sick room was a

[Source 3 | Page 33]
slapped his thigh in a paroxysm of amusement.
“The fun of it is,” he cried, “that that fool Lestrade,
who thinks himself so smart, has gone off upon the
wrong track altogether. He is after the secretary
Stangerson, who had no more to do with the crime
than the babe unborn. I have no doubt that he has
caught him by this time.”
The idea tickled Gregson so much that he laughed
until he choked.
“And how did you get your clue?”
“Ah, I’ll tell you all about it. Of course, Doctor
Watson, this is strictly between ourselves. The ﬁrst dif-
ﬁculty which we had to contend with was the ﬁnding
of this American’s antecedents. Some people would
have waited until their advertisements were answered,
or until parties came forward and volunteered infor-
mation. That is not Tobias Gregson’s way of going to
work. You remember the hat beside the dead man?”
“Yes,” said Holmes; “by John Underwood and
Sons, 129, Camberwell Road.”
Gregson looked quite crest-fallen.

[Source 4 | Page 77]
to do, Miss Morstan?”
“That is exactly what I want to ask you.”
“Then we shall most certainly go. You and I
and—yes, why, Dr. Watson is the very man. Your cor-
respondent says two friends. He and I have worked
together before.”
“But would he come?” she asked, with something
appealing in her voice and expression.
“I should be proud and happy,” said I, fervently,
“if I can be of any service.”
“You are both very kind,” she answered. “I have
led a retired life, and have no friends whom I could
appeal to. If I am here at six it will do, I suppose?”
71

[Source 5 | Page 143]
glance from his small fat-encircled eyes.
“Try the settee,” said Holmes, relapsing into his
armchair and putting his ﬁngertips together, as was
his custom when in judicial moods. “I know, my dear
Watson, that you share my love of all that is bizarre
and outside the conventions and humdrum routine
of everyday life. You have shown your relish for it by
the enthusiasm which has prompted you to chronicle,
and, if you will excuse my saying so, somewhat to
embellish so many of my own little adventures.”
“Your cases have indeed been of the greatest inter-
est to me,” I observed.
“You will remember that I remarked the other day,
just before we went into the very simple problem
presented by Miss Mary Sutherland, that for strange
effects and extraordinary combinations we must go
to life itself, which is always far more daring than any
effort of the imagination.”
“A proposition which I took the liberty of doubt-
ing.”
“You did, Doctor, but none the less you must come

Question:
Who is Dr. Watson?

Answer:

In [24]:
from ollama import chat

response = chat(
    model="qwen3:1.7b",
    messages=[
        {
            "role": "user",
            "content": "Who is Sherlock Holmes?"
        }
    ]
)

print(response["message"]["content"])

Sherlock Holmes is a fictional detective created by **Arthur Conan Doyle** in the 1880s. He is one of the most iconic figures in detective fiction and is often regarded as one of the greatest detectives in literature. Here's a concise overview:

### Key Traits:
- **Analytical and Logical**: Holmes is renowned for his exceptional deductive reasoning, sharp mind, and ability to solve complex mysteries.
- **Witty and Sarcastic**: His dialogue is sharp, witty, and often laced with humor.
- **Unconventional**: He challenges traditional detective work by relying on logic, observation, and sometimes unconventional methods.

### Notable Works:
- **"The Adventure of the Blanched Soldier"** (1887): A classic story showcasing his deductive skills.
- **"The Adventure of the Dancing Men"** (1891): A story where Holmes uses a unique pattern to solve a mystery.
- **"The Adventure of the Murders at the Old House"** (1892): A pivotal tale involving a haunted house and a murder.

### Legacy:
- Holmes is a cornerstone of the detective genre, influencing countless authors and popular culture.
- His character has been adapted into films, TV shows, and novels, cementing his place in global pop culture.
- He is often celebrated for blending intellect with humor, making him a timeless figure in literature.

### Summary:
Sherlock Holmes is a brilliant, eccentric detective whose stories explore the intersection of logic, crime, and human nature. His legacy lives on in the hearts of fans worldwide.

In [25]:
question = "Who is Dr. Watson?"

retrieved = retrieve_documents(question, top_k=5)

prompt = build_prompt(question, retrieved)

response = chat(
    model="qwen3:1.7b",
    messages=[
        {
            "role": "user",
            "content": prompt
        }
    ]
)

answer = response["message"]["content"]

print(answer)

Dr. Watson is the companion and friend of Sherlock Holmes, as mentioned in the provided context. He is described as a man of European reputation, a widower, and a key figure in Holmes's investigations. The context references his role in discussing cases and his relationship with Holmes, particularly in the context of solving mysteries.

Relevant source:
[Source 1 | Page 940]
[Source 2 | Page 809]

In [26]:
def ask_rag(question, top_k=5):
    # Retrieve relevant chunks
    retrieved_chunks = retrieve_documents(question, top_k=top_k)

    # Build grounded prompt
    prompt = build_prompt(question, retrieved_chunks)

    # Generate answer using Ollama
    response = chat(
        model="qwen3:1.7b",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    answer = response["message"]["content"]

    return answer, retrieved_chunks

In [27]:
answer, sources = ask_rag("Who is Dr. Watson?")

print(answer)

print("\nRetrieved Sources:")
for source in sources:
    print(
        f"- Page {source['page_number']} "
        f"(distance: {source['distance']:.4f})"
    )

Dr. Watson is the narrator of *The Complete Sherlock Holmes* series, a close companion and friend of Sherlock Holmes. He is mentioned in the context as a key figure in Holmes's investigations, often interacting with him and providing background details.

Relevant sources:
- **Source 2 | Page 809**: Watson is described as a friend of Holmes and someone he has worked with.
- **Source 3 | Page 33**: Watson is referred to as "Doctor Watson" in a conversation involving Holmes.
- **Source 4 | Page 77**: Watson is explicitly called the "very man" by the narrator, indicating his role as a trusted companion.

Thus, Dr. Watson is the narrator and a central figure in the stories, often collaborating with Holmes.

Retrieved Sources:
- Page 940 (distance: 0.8233)
- Page 809 (distance: 0.8585)
- Page 33 (distance: 0.8726)
- Page 77 (distance: 0.8879)
- Page 143 (distance: 0.8914)

## 2.6 Evaluation

The RAG system is evaluated using a set of test questions covering
different aspects of the Sherlock Holmes corpus.

For each question, we examine:

- Whether the retrieved chunks are relevant
- Whether the generated answer is grounded in the retrieved context
- Whether the answer is factually correct
- The source pages used to support the answer
- Failure cases and possible improvements

In [28]:
evaluation_questions = [
    "Who is Dr. Watson?",
    "Who is Sherlock Holmes?",
    "Where does Sherlock Holmes live?",
    "Who is Mrs. Hudson?",
    "What is Sherlock Holmes's profession?",
    "What is Dr. Watson's profession?",
    "Who is Inspector Lestrade?",
    "What is the relationship between Holmes and Watson?",
    "What kind of cases does Sherlock Holmes investigate?",
    "Who is Professor Moriarty?"
]

print("Number of evaluation questions:", len(evaluation_questions))

Number of evaluation questions: 10

In [29]:
evaluation_results = []

for question in evaluation_questions:
    print(f"\n{'=' * 80}")
    print(f"Question: {question}")
    
    answer, sources = ask_rag(question, top_k=5)
    
    source_pages = [source["page_number"] for source in sources]
    
    evaluation_results.append({
        "question": question,
        "answer": answer,
        "source_pages": source_pages
    })
    
    print("\nAnswer:")
    print(answer)
    
    print("\nRetrieved pages:")
    print(source_pages)

================================================================================
Question: Who is Dr. Watson?

Answer:
Dr. Watson is a companion and colleague of Sherlock Holmes in the context provided. He is mentioned as a fellow investigator and a close friend, often referred to in conversations between Holmes and others. The context does not specify his profession beyond his role as a friend and collaborator, and there is no detailed information about his background or other roles.

Relevant source: [Source 2 | Page 809] mentions him as a friend of the professor, and [Source 3 | Page 33] and [Source 5 | Page 143] refer to him as a colleague and companion of Holmes.

I could not find enough information in the provided context.

Retrieved pages:
[940, 809, 33, 77, 143]

================================================================================
Question: Who is Sherlock Holmes?

Answer:
Sherlock Holmes is a detective created by Arthur Conan Doyle, as stated in **Source 4 | Page 1** of *The Complete Sherlock Holmes*. He is portrayed as a brilliant, eccentric detective renowned for his sharp intellect and deductive skills. The context does not provide further details about his personal characteristics or background, but it establishes his role as a fictional character in Doyle's works.

**Source 4 | Page 1**
*The Complete Sherlock Holmes* by Arthur Conan Doyle.

Retrieved pages:
[123, 853, 283, 1, 419]

================================================================================
Question: Where does Sherlock Holmes live?

Answer:
Sherlock Holmes lives in a small farm upon the downs, five miles from Eastbourne, as stated in *The Adventures of Sherlock Holmes* (Source 1, Page 123). This detail is also mentioned in the preface of *The Case-Book of Sherlock Holmes* (Source 2, Page 745), but the specific location is explicitly outlined in Source 1.

Retrieved pages:
[123, 745, 283, 853, 419]

================================================================================
Question: Who is Mrs. Hudson?

Answer:
The context mentions Mrs. Hudson in Source 1, Page 579, describing her as the one who appeared with a lady’s card and handed it to Holmes. However, the context does not provide enough information to determine Mrs. Hudson’s full identity or background.

**Answer:**
The context mentions Mrs. Hudson in Source 1, Page 579, who brought a lady’s card to Holmes. However, no additional details about her identity are provided in the given text.

**Source:** Source 1, Page 579.

Retrieved pages:
[579, 569, 900, 770, 102]

================================================================================
Question: What is Sherlock Holmes's profession?

Answer:
I could not find enough information in the provided context.

The context does not explicitly state Sherlock Holmes's profession. While it mentions he lives in a farm and divides his time between philosophy and agriculture, these activities are described as his "time" rather than his profession. The text does not clarify whether he is a writer, farmer, or other professional. Thus, the answer cannot be determined from the given information.

Retrieved pages:
[123, 745, 853, 419, 283]

================================================================================
Question: What is Dr. Watson's profession?

Answer:
I could not find enough information in the provided context.

The context mentions Dr. Watson as "Doctor Watson" and refers to him as a "man of European reputation" and a "companion to Holmes," but it does not explicitly state his profession. The text does not provide details about his job or background.

Retrieved pages:
[940, 33, 143, 836, 77]

================================================================================
Question: Who is Inspector Lestrade?

Answer:
Inspector Lestrade is a police officer mentioned in the context as part of the investigation into the murder of Mr. Eduardo Lucas. He is described as a constable involved in the case, with details about his appearance and interactions with other characters (e.g., Watson and Colonel Ross). The relevant source pages are **Source 1 (Page 580)** and **Source 4 (Page 581)**.

In **Source 1 (Page 580)**, it is stated that Inspector Lestrade had taken the narrator into his confidence in the case. In **Source 4 (Page 581)**, Lestrade is depicted as a big constable who greeted Watson warmly upon entering the scene of the crime.

Retrieved pages:
[580, 290, 513, 581, 437]

================================================================================
Question: What is the relationship between Holmes and Watson?

Answer:
The relationship between Sherlock Holmes and Watson is that of a close, trusted companion and colleague. They collaborate in solving mysteries, share personal anecdotes, and have a mutual respect and friendship. Holmes often reflects on their partnership, acknowledging Watson's contributions and even apologizing for past experiments. Their relationship is characterized by trust, camaraderie, and the shared pursuit of solving complex cases.

Relevant sources:
[Source 3 | Page 143] – Holmes discusses their collaborative approach to cases and shared interests.
[Source 4 | Page 838] – Holmes apologizes to Watson, indicating a personal and trusted relationship.
[Source 2 | Page 861] – Holmes uses his detective skills to uncover secrets, highlighting their partnership.

Thus, their relationship is a close, professional bond with emotional depth.

Retrieved pages:
[981, 861, 143, 838, 940]

================================================================================
Question: What kind of cases does Sherlock Holmes investigate?

Answer:
Sherlock Holmes investigates cases that are initially commonplace but become increasingly complex, often involving murders or crimes that seem trivial at first but require profound deductive reasoning. The context highlights that such cases are "simple" but "extremely difﬁcult" and that Holmes must "construct our case for ourselves without any help from them."

Relevant sources:
[Source 3 | Page 167] discusses a "very serious case against the son of the murdered man" and mentions "simple cases which are so extremely difﬁcult."
[Source 5 | Page 566] emphasizes that the case "rises from the commonplace to the exceedingly remarkable," indicating Holmes's involvement in complex, seemingly simple but intricate crimes.

Retrieved pages:
[853, 123, 167, 283, 566]

================================================================================
Question: Who is Professor Moriarty?

Answer:
Professor Moriarty is a highly intelligent and cunning criminal mastermind who is renowned for his exceptional intellect and elaborate schemes. He is described as someone who has achieved great notoriety in London's criminal records, with no one else knowing his identity. He is portrayed as wealthy, with multiple banking accounts, and his actions are meticulously planned to avoid detection. The context emphasizes his ability to evade capture and his strategic use of financial resources.

Relevant sources:
[Source 1 | Page 410]
[Source 4 | Page 409]
[Source 3 | Page 675]

Retrieved pages:
[410, 410, 675, 409, 413]

In [30]:
for result in evaluation_results:
    print("\n" + "=" * 100)
    print("QUESTION:", result["question"])
    print("\nANSWER:")
    print(result["answer"])
    
    print("\nRETRIEVED CONTEXT:")
    for i, source in enumerate(
        retrieve_documents(result["question"], top_k=5),
        start=1
    ):
        print(f"\n--- Chunk {i} | Page {source['page_number']} ---")
        print(source["text"][:1500])

====================================================================================================
QUESTION: Who is Dr. Watson?

ANSWER:
Dr. Watson is a companion and colleague of Sherlock Holmes in the context provided. He is mentioned as a fellow investigator and a close friend, often referred to in conversations between Holmes and others. The context does not specify his profession beyond his role as a friend and collaborator, and there is no detailed information about his background or other roles.

Relevant source: [Source 2 | Page 809] mentions him as a friend of the professor, and [Source 3 | Page 33] and [Source 5 | Page 143] refer to him as a colleague and companion of Holmes.

I could not find enough information in the provided context.

RETRIEVED CONTEXT:

--- Chunk 1 | Page 940 ---
“As you like, Mr. Holmes. You will, I am sure,
understand my having some reserves in the matter.”
“You will appreciate it, Watson, when I tell you
that this gentleman, Mr. Trevor Bennett, is profes-
sional assistant to the great scientist, lives under his
roof, and is engaged to his only daughter. Certainly
we must agree that the professor has every claim upon
his loyalty and devotion. But it may best be shown
by taking the necessary steps to clear up this strange
mystery.”
“I hope so, Mr. Holmes. That is my one object.
Does Dr. Watson know the situation?”
“I have not had time to explain it.”
“Then perhaps I had better go over the ground
again before explaining some fresh developments.”
“I will do so myself,” said Holmes, “in order to
show that I have the events in their due order. The
professor, Watson, is a man of European reputation.
His life has been academic. There has never been a
breath of scandal. He is a widower with one daugh-

--- Chunk 2 | Page 809 ---
I am going for a doctor this very hour,’ said I. ‘Let it
be Watson, then,’ said he. I wouldn’t waste an hour
in coming to him, sir, or you may not see him alive.”
I was horriﬁed for I had heard nothing of his ill-
ness. I need not say that I rushed for my coat and my
hat. As we drove back I asked for the details.
“There is little I can tell you, sir. He has been work-
ing at a case down at Rotherhithe, in an alley near the
river, and he has brought this illness back with him.
He took to his bed on Wednesday afternoon and has
never moved since. For these three days neither food
nor drink has passed his lips.”
“Good God! Why did you not call in a doctor?”
“He wouldn’t have it, sir. You know how mas-
terful he is. I didn’t dare to disobey him. But he’s
not long for this world, as you’ll see for yourself the
moment that you set eyes on him.”
He was indeed a deplorable spectacle. In the dim
light of a foggy November day the sick room was a

--- Chunk 3 | Page 33 ---
slapped his thigh in a paroxysm of amusement.
“The fun of it is,” he cried, “that that fool Lestrade,
who thinks himself so smart, has gone off upon the
wrong track altogether. He is after the secretary
Stangerson, who had no more to do with the crime
than the babe unborn. I have no doubt that he has
caught him by this time.”
The idea tickled Gregson so much that he laughed
until he choked.
“And how did you get your clue?”
“Ah, I’ll tell you all about it. Of course, Doctor
Watson, this is strictly between ourselves. The ﬁrst dif-
ﬁculty which we had to contend with was the ﬁnding
of this American’s antecedents. Some people would
have waited until their advertisements were answered,
or until parties came forward and volunteered infor-
mation. That is not Tobias Gregson’s way of going to
work. You remember the hat beside the dead man?”
“Yes,” said Holmes; “by John Underwood and
Sons, 129, Camberwell Road.”
Gregson looked quite crest-fallen.

--- Chunk 4 | Page 77 ---
to do, Miss Morstan?”
“That is exactly what I want to ask you.”
“Then we shall most certainly go. You and I
and—yes, why, Dr. Watson is the very man. Your cor-
respondent says two friends. He and I have worked
together before.”
“But would he come?” she asked, with something
appealing in her voice and expression.
“I should be proud and happy,” said I, fervently,
“if I can be of any service.”
“You are both very kind,” she answered. “I have
led a retired life, and have no friends whom I could
appeal to. If I am here at six it will do, I suppose?”
71

--- Chunk 5 | Page 143 ---
glance from his small fat-encircled eyes.
“Try the settee,” said Holmes, relapsing into his
armchair and putting his ﬁngertips together, as was
his custom when in judicial moods. “I know, my dear
Watson, that you share my love of all that is bizarre
and outside the conventions and humdrum routine
of everyday life. You have shown your relish for it by
the enthusiasm which has prompted you to chronicle,
and, if you will excuse my saying so, somewhat to
embellish so many of my own little adventures.”
“Your cases have indeed been of the greatest inter-
est to me,” I observed.
“You will remember that I remarked the other day,
just before we went into the very simple problem
presented by Miss Mary Sutherland, that for strange
effects and extraordinary combinations we must go
to life itself, which is always far more daring than any
effort of the imagination.”
“A proposition which I took the liberty of doubt-
ing.”
“You did, Doctor, but none the less you must come

====================================================================================================
QUESTION: Who is Sherlock Holmes?

ANSWER:
Sherlock Holmes is a detective created by Arthur Conan Doyle, as stated in **Source 4 | Page 1** of *The Complete Sherlock Holmes*. He is portrayed as a brilliant, eccentric detective renowned for his sharp intellect and deductive skills. The context does not provide further details about his personal characteristics or background, but it establishes his role as a fictional character in Doyle's works.

**Source 4 | Page 1**
*The Complete Sherlock Holmes* by Arthur Conan Doyle.

RETRIEVED CONTEXT:

--- Chunk 1 | Page 123 ---
The Adventures of Sherlock Holmes

--- Chunk 2 | Page 853 ---
The Case-Book of Sherlock Holmes

--- Chunk 3 | Page 283 ---
The Memoirs of Sherlock Holmes

--- Chunk 4 | Page 1 ---
The Complete Sherlock Holmes
Arthur Conan Doyle

--- Chunk 5 | Page 419 ---
The Return of Sherlock Holmes

====================================================================================================
QUESTION: Where does Sherlock Holmes live?

ANSWER:
Sherlock Holmes lives in a small farm upon the downs, five miles from Eastbourne, as stated in *The Adventures of Sherlock Holmes* (Source 1, Page 123). This detail is also mentioned in the preface of *The Case-Book of Sherlock Holmes* (Source 2, Page 745), but the specific location is explicitly outlined in Source 1.

RETRIEVED CONTEXT:

--- Chunk 1 | Page 123 ---
The Adventures of Sherlock Holmes

--- Chunk 2 | Page 745 ---
Preface
Preface
The friends of Mr. Sherlock Holmes will be glad to learn that he is still alive and well, though
somewhat crippled by occasional attacks of rheumatism. He has, for many years, lived in a small
farm upon the downs ﬁve miles from Eastbourne, where his time is divided between philosophy
and agriculture. During this period of rest he has refused the most princely offers to take up
various cases, having determined that his retirement was a permanent one. The approach of the
German war caused him, however, to lay his remarkable combination of intellectual and practical
activity at the disposal of the government, with historical results which are recounted in His Last
Bow. Several previous experiences which have lain long in my portfolio have been added to His
Last Bow so as to complete the volume.
John H. Watson, M. D.
739

--- Chunk 3 | Page 283 ---
The Memoirs of Sherlock Holmes

--- Chunk 4 | Page 853 ---
The Case-Book of Sherlock Holmes

--- Chunk 5 | Page 419 ---
The Return of Sherlock Holmes

====================================================================================================
QUESTION: Who is Mrs. Hudson?

ANSWER:
The context mentions Mrs. Hudson in Source 1, Page 579, describing her as the one who appeared with a lady’s card and handed it to Holmes. However, the context does not provide enough information to determine Mrs. Hudson’s full identity or background.

**Answer:**
The context mentions Mrs. Hudson in Source 1, Page 579, who brought a lady’s card to Holmes. However, no additional details about her identity are provided in the given text.

**Source:** Source 1, Page 579.

RETRIEVED CONTEXT:

--- Chunk 1 | Page 579 ---
The Adventure of the Second Stain
Terrace. The other secret agents whom I have named
live in the extreme West-end. It was easier, therefore,
for Lucas than for the others to establish a connection
or receive a message from the European Secretary’s
household—a small thing, and yet where events are
compressed into a few hours it may prove essential.
Halloa! what have we here?”
Mrs. Hudson had appeared with a lady’s card
upon her salver. Holmes glanced at it, raised his
eyebrows, and handed it over to me.
“Ask Lady Hilda Trelawney Hope if she will be
kind enough to step up,” said he.
A moment later our modest apartment, already so
distinguished that morning, was further honoured by
the entrance of the most lovely woman in London. I
had often heard of the beauty of the youngest daugh-
ter of the Duke of Belminster, but no description of it,
and no contemplation of colourless photographs, had
prepared me for the subtle, delicate charm and the

--- Chunk 2 | Page 569 ---
herself away on a penniless sailor. That’s how I loved
Mary Fraser.
“Well, I never thought to see her again; but last
voyage I was promoted, and the new boat was not yet
launched, so I had to wait for a couple of months with
my people at Sydenham. One day out in a country
lane I met Theresa Wright, her old maid. She told
me about her, about him, about everything. I tell you,
gentlemen, it nearly drove me mad. This drunken
hound, that he should dare to raise his hand to her
whose boots he was not worthy to lick! I met Theresa
563

--- Chunk 3 | Page 900 ---
Isadora Klein.”
We had taken a cab and were speeding to some
address in Grosvenor Square. Holmes had been sunk
in thought, but he roused himself suddenly.
“By the way, Watson, I suppose you see it all
clearly?”
“No, I can’t say that I do. I only gather that we are
going to see the lady who is behind all this mischief.”
“Exactly! But does the name Isadora Klein convey
nothing to you? She was, of course, the celebrated
beauty. There was never a woman to touch her. She is
pure Spanish, the real blood of the masterful Conquis-
tadors, and her people have been leaders in Pernam-
buco for generations. She married the aged German
sugar king, Klein, and presently found herself the
richest as well as the most lovely widow upon earth.
Then there was an interval of adventure when she
pleased her own tastes. She had several lovers, and
Douglas Maberley, one of the most striking men in
London, was one of them. It was by all accounts
more than an adventure with him. He was not a soci-

--- Chunk 4 | Page 770 ---
Sarah and Mary.”
“And here at my elbow is another portrait, taken
at Liverpool, of your younger sister, in the company
of a man who appears to be a steward by his uniform.
I observe that she was unmarried at the time.”
“You are very quick at observing.”
“That is my trade.”
“Well, you are quite right. But she was married to
Mr. Browner a few days afterwards. He was on the
South American line when that was taken, but he was
so fond of her that he couldn’t abide to leave her for
so long, and he got into the Liverpool and London
boats.”
“Ah, the Conqueror, perhaps?”
764

--- Chunk 5 | Page 102 ---
is no news, nor has Mrs. Smith heard of her husband.
I shall come to the conclusion soon that they have
scuttled the craft. But there are objections to that.”
“Or that Mrs. Smith has put us on a wrong scent.”
“No, I think that may be dismissed. I had inquiries
made, and there is a launch of that description.”
“Could it have gone up the river?”
“I have considered that possibility too, and there is
a search-party who will work up as far as Richmond.
If no news comes to-day, I shall start off myself to-
morrow, and go for the men rather than the boat. But
surely, surely, we shall hear something.”
We did not, however. Not a word came to us ei-
ther from Wiggins or from the other agencies. There
were articles in most of the papers upon the Norwood
tragedy. They all appeared to be rather hostile to the
unfortunate Thaddeus Sholto. No fresh details were
to be found, however, in any of them, save that an in-
quest was to be held upon the following day. I walked

====================================================================================================
QUESTION: What is Sherlock Holmes's profession?

ANSWER:
I could not find enough information in the provided context.

The context does not explicitly state Sherlock Holmes's profession. While it mentions he lives in a farm and divides his time between philosophy and agriculture, these activities are described as his "time" rather than his profession. The text does not clarify whether he is a writer, farmer, or other professional. Thus, the answer cannot be determined from the given information.

RETRIEVED CONTEXT:

--- Chunk 1 | Page 123 ---
The Adventures of Sherlock Holmes

--- Chunk 2 | Page 745 ---
Preface
Preface
The friends of Mr. Sherlock Holmes will be glad to learn that he is still alive and well, though
somewhat crippled by occasional attacks of rheumatism. He has, for many years, lived in a small
farm upon the downs ﬁve miles from Eastbourne, where his time is divided between philosophy
and agriculture. During this period of rest he has refused the most princely offers to take up
various cases, having determined that his retirement was a permanent one. The approach of the
German war caused him, however, to lay his remarkable combination of intellectual and practical
activity at the disposal of the government, with historical results which are recounted in His Last
Bow. Several previous experiences which have lain long in my portfolio have been added to His
Last Bow so as to complete the volume.
John H. Watson, M. D.
739

--- Chunk 3 | Page 853 ---
The Case-Book of Sherlock Holmes

--- Chunk 4 | Page 419 ---
The Return of Sherlock Holmes

--- Chunk 5 | Page 283 ---
The Memoirs of Sherlock Holmes

====================================================================================================
QUESTION: What is Dr. Watson's profession?

ANSWER:
I could not find enough information in the provided context.

The context mentions Dr. Watson as "Doctor Watson" and refers to him as a "man of European reputation" and a "companion to Holmes," but it does not explicitly state his profession. The text does not provide details about his job or background.

RETRIEVED CONTEXT:

--- Chunk 1 | Page 940 ---
“As you like, Mr. Holmes. You will, I am sure,
understand my having some reserves in the matter.”
“You will appreciate it, Watson, when I tell you
that this gentleman, Mr. Trevor Bennett, is profes-
sional assistant to the great scientist, lives under his
roof, and is engaged to his only daughter. Certainly
we must agree that the professor has every claim upon
his loyalty and devotion. But it may best be shown
by taking the necessary steps to clear up this strange
mystery.”
“I hope so, Mr. Holmes. That is my one object.
Does Dr. Watson know the situation?”
“I have not had time to explain it.”
“Then perhaps I had better go over the ground
again before explaining some fresh developments.”
“I will do so myself,” said Holmes, “in order to
show that I have the events in their due order. The
professor, Watson, is a man of European reputation.
His life has been academic. There has never been a
breath of scandal. He is a widower with one daugh-

--- Chunk 2 | Page 33 ---
slapped his thigh in a paroxysm of amusement.
“The fun of it is,” he cried, “that that fool Lestrade,
who thinks himself so smart, has gone off upon the
wrong track altogether. He is after the secretary
Stangerson, who had no more to do with the crime
than the babe unborn. I have no doubt that he has
caught him by this time.”
The idea tickled Gregson so much that he laughed
until he choked.
“And how did you get your clue?”
“Ah, I’ll tell you all about it. Of course, Doctor
Watson, this is strictly between ourselves. The ﬁrst dif-
ﬁculty which we had to contend with was the ﬁnding
of this American’s antecedents. Some people would
have waited until their advertisements were answered,
or until parties came forward and volunteered infor-
mation. That is not Tobias Gregson’s way of going to
work. You remember the hat beside the dead man?”
“Yes,” said Holmes; “by John Underwood and
Sons, 129, Camberwell Road.”
Gregson looked quite crest-fallen.

--- Chunk 3 | Page 143 ---
glance from his small fat-encircled eyes.
“Try the settee,” said Holmes, relapsing into his
armchair and putting his ﬁngertips together, as was
his custom when in judicial moods. “I know, my dear
Watson, that you share my love of all that is bizarre
and outside the conventions and humdrum routine
of everyday life. You have shown your relish for it by
the enthusiasm which has prompted you to chronicle,
and, if you will excuse my saying so, somewhat to
embellish so many of my own little adventures.”
“Your cases have indeed been of the greatest inter-
est to me,” I observed.
“You will remember that I remarked the other day,
just before we went into the very simple problem
presented by Miss Mary Sutherland, that for strange
effects and extraordinary combinations we must go
to life itself, which is always far more daring than any
effort of the imagination.”
“A proposition which I took the liberty of doubt-
ing.”
“You did, Doctor, but none the less you must come

--- Chunk 4 | Page 836 ---
“Then I have wasted my time and need not pro-
long my visit.” The famous doctor strode out of our
cottage in considerable ill-humour, and within ﬁve
minutes Holmes had followed him. I saw him no
more until the evening, when he returned with a slow
step and haggard face which assured me that he had
made no great progress with his investigation. He
glanced at a telegram which awaited him and threw
it into the grate.
“From the Plymouth hotel, Watson,” he said. “I
learned the name of it from the vicar, and I wired to
make certain that Dr. Leon Sterndale’s account was
true. It appears that he did indeed spend last night
there, and that he has actually allowed some of his
baggage to go on to Africa, while he returned to be
present at this investigation. What do you make of
that, Watson?”
“He is deeply interested.”
“Deeply interested—yes. There is a thread here
which we had not yet grasped and which might lead
us through the tangle. Cheer up, Watson, for I am

--- Chunk 5 | Page 77 ---
to do, Miss Morstan?”
“That is exactly what I want to ask you.”
“Then we shall most certainly go. You and I
and—yes, why, Dr. Watson is the very man. Your cor-
respondent says two friends. He and I have worked
together before.”
“But would he come?” she asked, with something
appealing in her voice and expression.
“I should be proud and happy,” said I, fervently,
“if I can be of any service.”
“You are both very kind,” she answered. “I have
led a retired life, and have no friends whom I could
appeal to. If I am here at six it will do, I suppose?”
71

====================================================================================================
QUESTION: Who is Inspector Lestrade?

ANSWER:
Inspector Lestrade is a police officer mentioned in the context as part of the investigation into the murder of Mr. Eduardo Lucas. He is described as a constable involved in the case, with details about his appearance and interactions with other characters (e.g., Watson and Colonel Ross). The relevant source pages are **Source 1 (Page 580)** and **Source 4 (Page 581)**.


### Evaluation Results

The system was tested using 10 questions covering character identity,
relationships, professions, locations, and types of cases.

Each result was reviewed based on retrieval relevance, answer
grounding, and factual correctness.

The evaluation also revealed several failure cases where the retriever
returned weak or insufficient context. In such cases, the language
model sometimes refused to answer, while in other cases it generated
information that was not directly supported by the retrieved chunks.

In [31]:
evaluation_labels = [
    {
        "question": "Who is Dr. Watson?",
        "retrieval": "Partial",
        "grounded": True,
        "correct": "Partial",
        "notes": "Retrieved relevant mentions, but no clear profession/background."
    },
    {
        "question": "Who is Sherlock Holmes?",
        "retrieval": "Weak",
        "grounded": False,
        "correct": "Partial",
        "notes": "Retrieved mostly book titles; answer included unsupported general knowledge."
    },
    {
        "question": "Where does Sherlock Holmes live?",
        "retrieval": "Strong",
        "grounded": True,
        "correct": True,
        "notes": "Page 745 directly states that Holmes lives on a small farm near Eastbourne."
    },
    {
        "question": "Who is Mrs. Hudson?",
        "retrieval": "Partial",
        "grounded": True,
        "correct": "Partial",
        "notes": "Retrieved a mention of Mrs. Hudson but not a direct description of her role."
    },
    {
        "question": "What is Sherlock Holmes's profession?",
        "retrieval": "Weak",
        "grounded": True,
        "correct": False,
        "notes": "Retrieved context did not explicitly provide his profession."
    },
    {
        "question": "What is Dr. Watson's profession?",
        "retrieval": "Weak",
        "grounded": True,
        "correct": False,
        "notes": "Retrieved context mentioned 'Doctor Watson' but did not directly explain his profession."
    },
    {
        "question": "Who is Inspector Lestrade?",
        "retrieval": "Strong",
        "grounded": True,
        "correct": True,
        "notes": "Retrieved chunks directly describe Lestrade and his involvement in investigations."
    },
    {
        "question": "What is the relationship between Holmes and Watson?",
        "retrieval": "Strong",
        "grounded": True,
        "correct": True,
        "notes": "Retrieved chunks directly support their friendship and collaboration."
    },
    {
        "question": "What kind of cases does Sherlock Holmes investigate?",
        "retrieval": "Strong",
        "grounded": True,
        "correct": True,
        "notes": "Retrieved chunks discuss difficult crimes and investigations."
    },
    {
        "question": "Who is Professor Moriarty?",
        "retrieval": "Strong",
        "grounded": True,
        "correct": True,
        "notes": "Retrieved chunks directly describe Moriarty's criminal activities and intellect."
    }
]

In [32]:
import pandas as pd

evaluation_df = pd.DataFrame(evaluation_labels)

evaluation_df

,question,retrieval,grounded,correct,notes
0,Who is Dr. Watson?,Partial,True,Partial,"Retrieved relevant mentions, but no clear prof..."
1,Who is Sherlock Holmes?,Weak,False,Partial,Retrieved mostly book titles; answer included ...
2,Where does Sherlock Holmes live?,Strong,True,True,Page 745 directly states that Holmes lives on ...
3,Who is Mrs. Hudson?,Partial,True,Partial,Retrieved a mention of Mrs. Hudson but not a d...
4,What is Sherlock Holmes's profession?,Weak,True,False,Retrieved context did not explicitly provide h...
5,What is Dr. Watson's profession?,Weak,True,False,Retrieved context mentioned 'Doctor Watson' bu...
6,Who is Inspector Lestrade?,Strong,True,True,Retrieved chunks directly describe Lestrade an...
7,What is the relationship between Holmes and Wa...,Strong,True,True,Retrieved chunks directly support their friend...
8,What kind of cases does Sherlock Holmes invest...,Strong,True,True,Retrieved chunks discuss difficult crimes and ...
9,Who is Professor Moriarty?,Strong,True,True,Retrieved chunks directly describe Moriarty's ...

In [33]:
question = "What is Sherlock Holmes's profession?"

retrieved = retrieve_documents(question, top_k=10)

for i, chunk in enumerate(retrieved, start=1):
    print(f"\n{'=' * 70}")
    print(f"Rank {i} | Page {chunk['page_number']} | Distance: {chunk['distance']:.4f}")
    print(chunk["text"])

======================================================================
Rank 1 | Page 123 | Distance: 0.5755
The Adventures of Sherlock Holmes

======================================================================
Rank 2 | Page 745 | Distance: 0.6006
Preface
Preface
The friends of Mr. Sherlock Holmes will be glad to learn that he is still alive and well, though
somewhat crippled by occasional attacks of rheumatism. He has, for many years, lived in a small
farm upon the downs ﬁve miles from Eastbourne, where his time is divided between philosophy
and agriculture. During this period of rest he has refused the most princely offers to take up
various cases, having determined that his retirement was a permanent one. The approach of the
German war caused him, however, to lay his remarkable combination of intellectual and practical
activity at the disposal of the government, with historical results which are recounted in His Last
Bow. Several previous experiences which have lain long in my portfolio have been added to His
Last Bow so as to complete the volume.
John H. Watson, M. D.
739

======================================================================
Rank 3 | Page 853 | Distance: 0.6171
The Case-Book of Sherlock Holmes

======================================================================
Rank 4 | Page 419 | Distance: 0.6613
The Return of Sherlock Holmes

======================================================================
Rank 5 | Page 283 | Distance: 0.6770
The Memoirs of Sherlock Holmes

======================================================================
Rank 6 | Page 855 | Distance: 0.7080
Preface
Preface
I fear that Mr. Sherlock Holmes may become like one of those popular tenors who, having
outlived their time, are still tempted to make repeated farewell bows to their indulgent audiences.
This must cease and he must go the way of all ﬂesh, material or imaginary. One likes to think that
there is some fantastic limbo for the children of imagination, some strange, impossible place where
the beaux of Fielding may still make love to the belles of Richardson, where Scott’s heroes still may
strut, Dickens’s delightful Cockneys still raise a laugh, and Thackeray’s worldlings continue to
carry on their reprehensible careers. Perhaps in some humble corner of such a Valhalla, Sherlock
and his Watson may for a time ﬁnd a place, while some more astute sleuth with some even less
astute comrade may ﬁll the stage which they have vacated.
His career has been a long one—though it is possible to exaggerate it; decrepit gentlemen who

======================================================================
Rank 7 | Page 234 | Distance: 0.7306
to Baker Street.
Sherlock Holmes was, as I expected, lounging
about his sitting-room in his dressing-gown, read-
ing the agony column of The Times and smoking his
before-breakfast pipe, which was composed of all the
plugs and dottles left from his smokes of the day be-
fore, all carefully dried and collected on the corner of
the mantelpiece. He received us in his quietly genial
fashion, ordered fresh rashers and eggs, and joined
us in a hearty meal. When it was concluded he set-
tled our new acquaintance upon the sofa, placed a
pillow beneath his head, and laid a glass of brandy
and water within his reach.
“It is easy to see that your experience has been no
common one, Mr. Hatherley,” said he. “Pray, lie down
there and make yourself absolutely at home. Tell us
what you can, but stop when you are tired and keep
up your strength with a little stimulant.”
“Thank you,” said my patient. “but I have felt an-
other man since the doctor bandaged me, and I think

======================================================================
Rank 8 | Page 1 | Distance: 0.7318
The Complete Sherlock Holmes
Arthur Conan Doyle

======================================================================
Rank 9 | Page 143 | Distance: 0.7345
of extreme chagrin and discontent upon his features.
Sherlock Holmes’ quick eye took in my occupa-
tion, and he shook his head with a smile as he noticed
my questioning glances. “Beyond the obvious facts
that he has at some time done manual labour, that he
takes snuff, that he is a Freemason, that he has been
in China, and that he has done a considerable amount
of writing lately, I can deduce nothing else.”
Mr. Jabez Wilson started up in his chair, with his
foreﬁnger upon the paper, but his eyes upon my com-
panion.
“How, in the name of good-fortune, did you know
all that, Mr. Holmes?” he asked. “How did you know,
for example, that I did manual labour. It’s as true as
gospel, for I began as a ship’s carpenter.”
137

======================================================================
Rank 10 | Page 200 | Distance: 0.7422
points about which I wished to be absolutely clear.
We shall now have a little supper and then retire, for
we may have a very busy day to-morrow.”
A large and comfortable double-bedded room had
been placed at our disposal, and I was quickly be-
tween the sheets, for I was weary after my night of
adventure. Sherlock Holmes was a man, however,
who, when he had an unsolved problem upon his
mind, would go for days, and even for a week, with-
out rest, turning it over, rearranging his facts, looking
at it from every point of view until he had either
fathomed it or convinced himself that his data were
insufﬁcient. It was soon evident to me that he was
now preparing for an all-night sitting. He took off
his coat and waistcoat, put on a large blue dressing-
gown, and then wandered about the room collecting
pillows from his bed and cushions from the sofa and
armchairs. With these he constructed a sort of Eastern
divan, upon which he perched himself cross-legged,

In [34]:
question = "What does Sherlock Holmes do for a living?"

retrieved = retrieve_documents(question, top_k=10)

for i, chunk in enumerate(retrieved, start=1):
    print(f"\n{'=' * 70}")
    print(
        f"Rank {i} | Page {chunk['page_number']} "
        f"| Distance: {chunk['distance']:.4f}"
    )
    print(chunk["text"])

======================================================================
Rank 1 | Page 123 | Distance: 0.5746
The Adventures of Sherlock Holmes

======================================================================
Rank 2 | Page 745 | Distance: 0.6094
Preface
Preface
The friends of Mr. Sherlock Holmes will be glad to learn that he is still alive and well, though
somewhat crippled by occasional attacks of rheumatism. He has, for many years, lived in a small
farm upon the downs ﬁve miles from Eastbourne, where his time is divided between philosophy
and agriculture. During this period of rest he has refused the most princely offers to take up
various cases, having determined that his retirement was a permanent one. The approach of the
German war caused him, however, to lay his remarkable combination of intellectual and practical
activity at the disposal of the government, with historical results which are recounted in His Last
Bow. Several previous experiences which have lain long in my portfolio have been added to His
Last Bow so as to complete the volume.
John H. Watson, M. D.
739

======================================================================
Rank 3 | Page 419 | Distance: 0.6632
The Return of Sherlock Holmes

======================================================================
Rank 4 | Page 283 | Distance: 0.6924
The Memoirs of Sherlock Holmes

======================================================================
Rank 5 | Page 853 | Distance: 0.7132
The Case-Book of Sherlock Holmes

======================================================================
Rank 6 | Page 855 | Distance: 0.7137
Preface
Preface
I fear that Mr. Sherlock Holmes may become like one of those popular tenors who, having
outlived their time, are still tempted to make repeated farewell bows to their indulgent audiences.
This must cease and he must go the way of all ﬂesh, material or imaginary. One likes to think that
there is some fantastic limbo for the children of imagination, some strange, impossible place where
the beaux of Fielding may still make love to the belles of Richardson, where Scott’s heroes still may
strut, Dickens’s delightful Cockneys still raise a laugh, and Thackeray’s worldlings continue to
carry on their reprehensible careers. Perhaps in some humble corner of such a Valhalla, Sherlock
and his Watson may for a time ﬁnd a place, while some more astute sleuth with some even less
astute comrade may ﬁll the stage which they have vacated.
His career has been a long one—though it is possible to exaggerate it; decrepit gentlemen who

======================================================================
Rank 7 | Page 898 | Distance: 0.7241
and I am going to see him now. When I get back I
may be clearer in the matter.”
I saw no more of Holmes during the day, but I
could well imagine how he spent it, for Langdale Pike
was his human book of reference upon all matters of
social scandal. This strange, languid creature spent
his waking hours in the bow window of a St. James’s
Street club and was the receiving-station as well as
the transmitter for all the gossip of the metropolis.
He made, it was said, a four-ﬁgure income by the
paragraphs which he contributed every week to the
garbage papers which cater to an inquisitive public.
If ever, far down in the turbid depths of London life,
there was some strange swirl or eddy, it was marked
with automatic exactness by this human dial upon
the surface. Holmes discreetly helped Langdale to
knowledge, and on occasion was helped in turn.
When I met my friend in his room early next
morning, I was conscious from his bearing that all
892

======================================================================
Rank 8 | Page 144 | Distance: 0.7337
note, Doctor, of the paper and the date.”
“It is The Morning Chronicle of April 27, 1890. Just
two months ago.”
“Very good. Now, Mr. Wilson?”
“Well, it is just as I have been telling you, Mr.
Sherlock Holmes,” said Jabez Wilson, mopping his
forehead; “I have a small pawnbroker’s business at
Coburg Square, near the City. It’s not a very large
affair, and of late years it has not done more than
just give me a living. I used to be able to keep two
assistants, but now I only keep one; and I would have
a job to pay him but that he is willing to come for half
wages so as to learn the business.”
“What is the name of this obliging youth?” asked
Sherlock Holmes.
“His name is Vincent Spaulding, and he’s not such
a youth, either. It’s hard to say his age. I should not
wish a smarter assistant, Mr. Holmes; and I know very
well that he could better himself and earn twice what
I am able to give him. But, after all, if he is satisﬁed,
why should I put ideas in his head?”

======================================================================
Rank 9 | Page 809 | Distance: 0.7395
The Adventure of the Dying Detective
M
rs. H udson, the landlady of Sherlock
Holmes, was a long-suffering woman. Not
only was her ﬁrst-ﬂoor ﬂat invaded at all
hours by throngs of singular and often
undesirable characters but her remarkable lodger
showed an eccentricity and irregularity in his life
which must have sorely tried her patience. His in-
credible untidiness, his addiction to music at strange
hours, his occasional revolver practice within doors,
his weird and often malodorous scientiﬁc experi-
ments, and the atmosphere of violence and danger
which hung around him made him the very worst
tenant in London. On the other hand, his payments
were princely. I have no doubt that the house might
have been purchased at the price which Holmes paid
for his rooms during the years that I was with him.
The landlady stood in the deepest awe of him
and never dared to interfere with him, however out-
rageous his proceedings might seem. She was fond

======================================================================
Rank 10 | Page 234 | Distance: 0.7479
to Baker Street.
Sherlock Holmes was, as I expected, lounging
about his sitting-room in his dressing-gown, read-
ing the agony column of The Times and smoking his
before-breakfast pipe, which was composed of all the
plugs and dottles left from his smokes of the day be-
fore, all carefully dried and collected on the corner of
the mantelpiece. He received us in his quietly genial
fashion, ordered fresh rashers and eggs, and joined
us in a hearty meal. When it was concluded he set-
tled our new acquaintance upon the sofa, placed a
pillow beneath his head, and laid a glass of brandy
and water within his reach.
“It is easy to see that your experience has been no
common one, Mr. Hatherley,” said he. “Pray, lie down
there and make yourself absolutely at home. Tell us
what you can, but stop when you are tired and keep
up your strength with a little stimulant.”
“Thank you,” said my patient. “but I have felt an-
other man since the doctor bandaged me, and I think

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

chunk_texts = [chunk["text"] for chunk in chunks]

tfidf_vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english"
)

tfidf_matrix = tfidf_vectorizer.fit_transform(chunk_texts)

print("TF-IDF matrix shape:", tfidf_matrix.shape)

TF-IDF matrix shape: (4519, 21891)

In [36]:
from sklearn.metrics.pairwise import cosine_similarity

def keyword_retrieve(query, top_k=10):
    query_vector = tfidf_vectorizer.transform([query])

    similarities = cosine_similarity(
        query_vector,
        tfidf_matrix
    ).flatten()

    top_indices = similarities.argsort()[-top_k:][::-1]

    results = []

    for index in top_indices:
        results.append({
            "text": chunks[index]["text"],
            "page_number": chunks[index]["page_number"],
            "chunk_index": chunks[index]["chunk_index"],
            "source": chunks[index]["source"],
            "score": similarities[index]
        })

    return results

In [37]:
question = "What is Sherlock Holmes's profession?"

keyword_results = keyword_retrieve(question, top_k=10)

for i, chunk in enumerate(keyword_results, start=1):
    print(f"\n{'=' * 70}")
    print(
        f"Rank {i} | Page {chunk['page_number']} "
        f"| TF-IDF Score: {chunk['score']:.4f}"
    )
    print(chunk["text"])

======================================================================
Rank 1 | Page 419 | TF-IDF Score: 0.3578
The Return of Sherlock Holmes

======================================================================
Rank 2 | Page 853 | TF-IDF Score: 0.3219
The Case-Book of Sherlock Holmes

======================================================================
Rank 3 | Page 123 | TF-IDF Score: 0.3030
The Adventures of Sherlock Holmes

======================================================================
Rank 4 | Page 283 | TF-IDF Score: 0.2719
The Memoirs of Sherlock Holmes

======================================================================
Rank 5 | Page 843 | TF-IDF Score: 0.2017
His Last Bow
An Epilogue of Sherlock Holmes

======================================================================
Rank 6 | Page 150 | TF-IDF Score: 0.1532
turn, we never know where to ﬁnd the man himself.
He’ll crack a crib in Scotland one week, and be raising
money to build an orphanage in Cornwall the next.
I’ve been on his track for years and have never set
eyes on him yet.”
“I hope that I may have the pleasure of introduc-
ing you to-night. I’ve had one or two little turns also
with Mr. John Clay, and I agree with you that he is at
the head of his profession. It is past ten, however, and
quite time that we started. If you two will take the
ﬁrst hansom, Watson and I will follow in the second.”
Sherlock Holmes was not very communicative dur-
ing the long drive and lay back in the cab humming
the tunes which he had heard in the afternoon. We
rattled through an endless labyrinth of gas-lit streets
until we emerged into Farrington Street.
“We are close there now,” my friend remarked.
“This fellow Merryweather is a bank director, and
personally interested in the matter. I thought it as

======================================================================
Rank 7 | Page 554 | TF-IDF Score: 0.1485
The Adventure of the Missing Three-Quarter
looked up with no very pleased expression upon his
dour features.
“I have heard your name, Mr. Sherlock Holmes,
and I am aware of your profession, one of which I by
no means approve.”
“In that, doctor, you will ﬁnd yourself in agree-
ment with every criminal in the country,” said my
friend, quietly.
“So far as your efforts are directed towards the
suppression of crime, sir, they must have the sup-
port of every reasonable member of the community,
though I cannot doubt that the ofﬁcial machinery is
amply sufﬁcient for the purpose. Where your calling
is more open to criticism is when you pry into the
secrets of private individuals, when you rake up fam-
ily matters which are better hidden, and when you
incidentally waste the time of men who are more busy
than yourself. At the present moment, for example,
I should be writing a treatise instead of conversing
with you.”
“No doubt, doctor; and yet the conversation may

======================================================================
Rank 8 | Page 1 | TF-IDF Score: 0.1453
The Complete Sherlock Holmes
Arthur Conan Doyle

======================================================================
Rank 9 | Page 698 | TF-IDF Score: 0.1407
started at once.”
We passed along the outer bounds of the Manor
House park until we came to a place where there was
a gap in the rails which fenced it. Through this we
slipped, and then in the gathering gloom we followed
Holmes until we had reached a shrubbery which lies
nearly opposite to the main door and the drawbridge.
The latter had not been raised. Holmes crouched
down behind the screen of laurels, and we all three
followed his example.
“Well, what are we to do now?” asked MacDonald
with some gruffness.
“Possess our souls in patience and make as little
noise as possible,” Holmes answered.
“What are we here for at all? I really think that
you might treat us with more frankness.”
Holmes laughed. “Watson insists that I am the
dramatist in real life,” said he. “Some touch of the
artist wells up within me, and calls insistently for a
well-staged performance. Surely our profession, Mr.
Mac, would be a drab and sordid one if we did not

======================================================================
Rank 10 | Page 20 | TF-IDF Score: 0.1404
A Study In Scarlet
Sherlock Holmes sniffed sardonically. “Lecoq was
a miserable bungler,” he said, in an angry voice; “he
had only one thing to recommend him, and that was
his energy. That book made me positively ill. The
question was how to identify an unknown prisoner. I
could have done it in twenty-four hours. Lecoq took
six months or so. It might be made a text-book for
detectives to teach them what to avoid.”
I felt rather indignant at having two characters
whom I had admired treated in this cavalier style. I
walked over to the window, and stood looking out
into the busy street. “This fellow may be very clever,”
I said to myself, “but he is certainly very conceited.”
“There are no crimes and no criminals in these
days,” he said, querulously. “What is the use of hav-
ing brains in our profession? I know well that I have
it in me to make my name famous. No man lives or
has ever lived who has brought the same amount of
study and of natural talent to the detection of crime

In [38]:
def hybrid_retrieve(query, top_k=5, candidate_k=20):
    semantic_results = retrieve_documents(query, top_k=candidate_k)
    keyword_results = keyword_retrieve(query, top_k=candidate_k)

    scores = {}
    chunk_data = {}

    # Semantic ranking
    for rank, result in enumerate(semantic_results, start=1):
        key = (
            result["page_number"],
            result["chunk_index"]
        )

        scores[key] = scores.get(key, 0) + 1 / (60 + rank)
        chunk_data[key] = result

    # Keyword ranking
    for rank, result in enumerate(keyword_results, start=1):
        key = (
            result["page_number"],
            result["chunk_index"]
        )

        scores[key] = scores.get(key, 0) + 1 / (60 + rank)
        chunk_data[key] = result

    # Sort by combined score
    ranked_keys = sorted(
        scores,
        key=scores.get,
        reverse=True
    )

    results = []

    for key in ranked_keys[:top_k]:
        result = chunk_data[key].copy()
        result["hybrid_score"] = scores[key]
        results.append(result)

    return results

In [39]:
question = "What is Sherlock Holmes's profession?"

hybrid_results = hybrid_retrieve(
    question,
    top_k=10,
    candidate_k=20
)

for i, chunk in enumerate(hybrid_results, start=1):
    print(f"\n{'=' * 70}")
    print(
        f"Rank {i} | Page {chunk['page_number']} "
        f"| Hybrid Score: {chunk['hybrid_score']:.4f}"
    )
    print(chunk["text"])

======================================================================
Rank 1 | Page 123 | Hybrid Score: 0.0323
The Adventures of Sherlock Holmes

======================================================================
Rank 2 | Page 419 | Hybrid Score: 0.0320
The Return of Sherlock Holmes

======================================================================
Rank 3 | Page 853 | Hybrid Score: 0.0320
The Case-Book of Sherlock Holmes

======================================================================
Rank 4 | Page 283 | Hybrid Score: 0.0310
The Memoirs of Sherlock Holmes

======================================================================
Rank 5 | Page 1 | Hybrid Score: 0.0294
The Complete Sherlock Holmes
Arthur Conan Doyle

======================================================================
Rank 6 | Page 745 | Hybrid Score: 0.0161
Preface
Preface
The friends of Mr. Sherlock Holmes will be glad to learn that he is still alive and well, though
somewhat crippled by occasional attacks of rheumatism. He has, for many years, lived in a small
farm upon the downs ﬁve miles from Eastbourne, where his time is divided between philosophy
and agriculture. During this period of rest he has refused the most princely offers to take up
various cases, having determined that his retirement was a permanent one. The approach of the
German war caused him, however, to lay his remarkable combination of intellectual and practical
activity at the disposal of the government, with historical results which are recounted in His Last
Bow. Several previous experiences which have lain long in my portfolio have been added to His
Last Bow so as to complete the volume.
John H. Watson, M. D.
739

======================================================================
Rank 7 | Page 843 | Hybrid Score: 0.0154
His Last Bow
An Epilogue of Sherlock Holmes

======================================================================
Rank 8 | Page 855 | Hybrid Score: 0.0152
Preface
Preface
I fear that Mr. Sherlock Holmes may become like one of those popular tenors who, having
outlived their time, are still tempted to make repeated farewell bows to their indulgent audiences.
This must cease and he must go the way of all ﬂesh, material or imaginary. One likes to think that
there is some fantastic limbo for the children of imagination, some strange, impossible place where
the beaux of Fielding may still make love to the belles of Richardson, where Scott’s heroes still may
strut, Dickens’s delightful Cockneys still raise a laugh, and Thackeray’s worldlings continue to
carry on their reprehensible careers. Perhaps in some humble corner of such a Valhalla, Sherlock
and his Watson may for a time ﬁnd a place, while some more astute sleuth with some even less
astute comrade may ﬁll the stage which they have vacated.
His career has been a long one—though it is possible to exaggerate it; decrepit gentlemen who

======================================================================
Rank 9 | Page 150 | Hybrid Score: 0.0152
turn, we never know where to ﬁnd the man himself.
He’ll crack a crib in Scotland one week, and be raising
money to build an orphanage in Cornwall the next.
I’ve been on his track for years and have never set
eyes on him yet.”
“I hope that I may have the pleasure of introduc-
ing you to-night. I’ve had one or two little turns also
with Mr. John Clay, and I agree with you that he is at
the head of his profession. It is past ten, however, and
quite time that we started. If you two will take the
ﬁrst hansom, Watson and I will follow in the second.”
Sherlock Holmes was not very communicative dur-
ing the long drive and lay back in the cab humming
the tunes which he had heard in the afternoon. We
rattled through an endless labyrinth of gas-lit streets
until we emerged into Farrington Street.
“We are close there now,” my friend remarked.
“This fellow Merryweather is a bank director, and
personally interested in the matter. I thought it as

======================================================================
Rank 10 | Page 234 | Hybrid Score: 0.0149
to Baker Street.
Sherlock Holmes was, as I expected, lounging
about his sitting-room in his dressing-gown, read-
ing the agony column of The Times and smoking his
before-breakfast pipe, which was composed of all the
plugs and dottles left from his smokes of the day be-
fore, all carefully dried and collected on the corner of
the mantelpiece. He received us in his quietly genial
fashion, ordered fresh rashers and eggs, and joined
us in a hearty meal. When it was concluded he set-
tled our new acquaintance upon the sofa, placed a
pillow beneath his head, and laid a glass of brandy
and water within his reach.
“It is easy to see that your experience has been no
common one, Mr. Hatherley,” said he. “Pray, lie down
there and make yourself absolutely at home. Tell us
what you can, but stop when you are tired and keep
up your strength with a little stimulant.”
“Thank you,” said my patient. “but I have felt an-
other man since the doctor bandaged me, and I think

In [40]:
def is_useful_chunk(text, min_words=20):
    return len(text.split()) >= min_words

In [41]:
useful_chunks = [
    chunk for chunk in chunks
    if is_useful_chunk(chunk["text"])
]

print("Original chunks:", len(chunks))
print("Useful chunks:", len(useful_chunks))
print("Removed chunks:", len(chunks) - len(useful_chunks))

Original chunks: 4519
Useful chunks: 4448
Removed chunks: 71

In [42]:
useful_texts = [chunk["text"] for chunk in useful_chunks]

tfidf_vectorizer_filtered = TfidfVectorizer(
    lowercase=True,
    stop_words="english"
)

tfidf_matrix_filtered = tfidf_vectorizer_filtered.fit_transform(
    useful_texts
)

print("Filtered TF-IDF matrix shape:", tfidf_matrix_filtered.shape)

Filtered TF-IDF matrix shape: (4448, 21889)

In [43]:
def keyword_retrieve_filtered(query, top_k=10):
    query_vector = tfidf_vectorizer_filtered.transform([query])

    similarities = cosine_similarity(
        query_vector,
        tfidf_matrix_filtered
    ).flatten()

    top_indices = similarities.argsort()[-top_k:][::-1]

    results = []

    for index in top_indices:
        results.append({
            "text": useful_chunks[index]["text"],
            "page_number": useful_chunks[index]["page_number"],
            "chunk_index": useful_chunks[index]["chunk_index"],
            "source": useful_chunks[index]["source"],
            "score": similarities[index]
        })

    return results

In [44]:
question = "What is Sherlock Holmes's profession?"

filtered_results = keyword_retrieve_filtered(
    question,
    top_k=10
)

for i, chunk in enumerate(filtered_results, start=1):
    print(f"\n{'=' * 70}")
    print(
        f"Rank {i} | Page {chunk['page_number']} "
        f"| TF-IDF Score: {chunk['score']:.4f}"
    )
    print(chunk["text"])

======================================================================
Rank 1 | Page 150 | TF-IDF Score: 0.1533
turn, we never know where to ﬁnd the man himself.
He’ll crack a crib in Scotland one week, and be raising
money to build an orphanage in Cornwall the next.
I’ve been on his track for years and have never set
eyes on him yet.”
“I hope that I may have the pleasure of introduc-
ing you to-night. I’ve had one or two little turns also
with Mr. John Clay, and I agree with you that he is at
the head of his profession. It is past ten, however, and
quite time that we started. If you two will take the
ﬁrst hansom, Watson and I will follow in the second.”
Sherlock Holmes was not very communicative dur-
ing the long drive and lay back in the cab humming
the tunes which he had heard in the afternoon. We
rattled through an endless labyrinth of gas-lit streets
until we emerged into Farrington Street.
“We are close there now,” my friend remarked.
“This fellow Merryweather is a bank director, and
personally interested in the matter. I thought it as

======================================================================
Rank 2 | Page 554 | TF-IDF Score: 0.1485
The Adventure of the Missing Three-Quarter
looked up with no very pleased expression upon his
dour features.
“I have heard your name, Mr. Sherlock Holmes,
and I am aware of your profession, one of which I by
no means approve.”
“In that, doctor, you will ﬁnd yourself in agree-
ment with every criminal in the country,” said my
friend, quietly.
“So far as your efforts are directed towards the
suppression of crime, sir, they must have the sup-
port of every reasonable member of the community,
though I cannot doubt that the ofﬁcial machinery is
amply sufﬁcient for the purpose. Where your calling
is more open to criticism is when you pry into the
secrets of private individuals, when you rake up fam-
ily matters which are better hidden, and when you
incidentally waste the time of men who are more busy
than yourself. At the present moment, for example,
I should be writing a treatise instead of conversing
with you.”
“No doubt, doctor; and yet the conversation may

======================================================================
Rank 3 | Page 20 | TF-IDF Score: 0.1404
A Study In Scarlet
Sherlock Holmes sniffed sardonically. “Lecoq was
a miserable bungler,” he said, in an angry voice; “he
had only one thing to recommend him, and that was
his energy. That book made me positively ill. The
question was how to identify an unknown prisoner. I
could have done it in twenty-four hours. Lecoq took
six months or so. It might be made a text-book for
detectives to teach them what to avoid.”
I felt rather indignant at having two characters
whom I had admired treated in this cavalier style. I
walked over to the window, and stood looking out
into the busy street. “This fellow may be very clever,”
I said to myself, “but he is certainly very conceited.”
“There are no crimes and no criminals in these
days,” he said, querulously. “What is the use of hav-
ing brains in our profession? I know well that I have
it in me to make my name famous. No man lives or
has ever lived who has brought the same amount of
study and of natural talent to the detection of crime

======================================================================
Rank 4 | Page 698 | TF-IDF Score: 0.1403
started at once.”
We passed along the outer bounds of the Manor
House park until we came to a place where there was
a gap in the rails which fenced it. Through this we
slipped, and then in the gathering gloom we followed
Holmes until we had reached a shrubbery which lies
nearly opposite to the main door and the drawbridge.
The latter had not been raised. Holmes crouched
down behind the screen of laurels, and we all three
followed his example.
“Well, what are we to do now?” asked MacDonald
with some gruffness.
“Possess our souls in patience and make as little
noise as possible,” Holmes answered.
“What are we here for at all? I really think that
you might treat us with more frankness.”
Holmes laughed. “Watson insists that I am the
dramatist in real life,” said he. “Some touch of the
artist wells up within me, and calls insistently for a
well-staged performance. Surely our profession, Mr.
Mac, would be a drab and sordid one if we did not

======================================================================
Rank 5 | Page 150 | TF-IDF Score: 0.1390
the stranger with deference. “Still, I confess that I
miss my rubber. It is the ﬁrst Saturday night for
seven-and-twenty years that I have not had my rub-
ber.”
“I think you will ﬁnd,” said Sherlock Holmes,
“that you will play for a higher stake to-night than
you have ever done yet, and that the play will be more
exciting. For you, Mr. Merryweather, the stake will be
some £30,000; and for you, Jones, it will be the man
upon whom you wish to lay your hands.”
“John Clay, the murderer, thief, smasher, and
forger. He’s a young man, Mr. Merryweather, but
he is at the head of his profession, and I would rather
have my bracelets on him than on any criminal in
London. He’s a remarkable man, is young John Clay.
His grandfather was a royal duke, and he himself has
been to Eton and Oxford. His brain is as cunning as
his ﬁngers, and though we meet signs of him at every
turn, we never know where to ﬁnd the man himself.
He’ll crack a crib in Scotland one week, and be raising

======================================================================
Rank 6 | Page 324 | TF-IDF Score: 0.1293
son and I were. His attack did not last long, however,
for when we undid his collar, and sprinkled the water
from one of the ﬁnger-glasses over his face, he gave a
gasp or two and sat up.
“ ‘Ah, boys,’ said he, forcing a smile, ‘I hope I
haven’t frightened you. Strong as I look, there is a
weak place in my heart, and it does not take much to
knock me over. I don’t know how you manage this,
Mr. Holmes, but it seems to me that all the detectives
of fact and of fancy would be children in your hands.
That’s your line of life, sir, and you may take the word
of a man who has seen something of the world.’
“And that recommendation, with the exaggerated
estimate of my ability with which he prefaced it, was,
if you will believe me, Watson, the very ﬁrst thing
which ever made me feel that a profession might be
made out of what had up to that time been the mer-
est hobby. At the moment, however, I was too much
concerned at the sudden illness of my host to think
of anything else.

======================================================================
Rank 7 | Page 380 | TF-IDF Score: 0.1247
the way into the hall. Through the glass paneling
I caught a glimpse of a large and luxurious room,
in which a considerable number of men were sit-
ting about and reading papers, each in his own little
nook. Holmes showed me into a small chamber which
looked out into Pall Mall, and then, leaving me for
a minute, he came back with a companion whom I
knew could only be his brother.
Mycroft Holmes was a much larger and stouter
man than Sherlock. His body was absolutely cor-
pulent, but his face, though massive, had preserved
something of the sharpness of expression which was
so remarkable in that of his brother. His eyes, which
were of a peculiarly light, watery gray, seemed to al-
ways retain that far-away, introspective look which I
had only observed in Sherlock’s when he was exerting
his full powers.
“I am glad to meet you, sir,” said he, putting out
a broad, fat hand like the ﬂipper of a seal. “I hear of
Sherlock everywhere since you became his chronicler.

======================================================================
Rank 8 | Page 459 | TF-IDF Score: 0.1218
to me, and she would have married me, I believe, if
I had taken over another profession; but she would
have nothing to do with anything on the cross. It was
only after her marriage to this Englishman that I was
able to ﬁnd out where she was. I wrote to her, but
got no answer. After that I came over, and, as letters
were no use, I put my messages where she could read
them.
“Well, I have been here a month now. I lived in
that farm, where I had a room down below, and could
get in and out every night, and no one the wiser. I
tried all I could to coax Elsie away. I knew that she
read the messages, for once she wrote an answer un-
der one of them. Then my temper got the better of me,
and I began to threaten her. She sent me a letter then,
imploring me to go away and saying that it would
break her heart if any scandal should come upon her
husband. She said that she would come down when
her husband was asleep at three in the morning, and
speak with me through the end window, if I would

======================================================================
Rank 9 | Page 228 | TF-IDF Score: 0.1205
The Adventure of the Speckled Band
“Holmes,” I cried, “I seem to see dimly what you
are hinting at. We are only just in time to prevent
some subtle and horrible crime.”
“Subtle enough and horrible enough. When a doc-
tor does go wrong he is the ﬁrst of criminals. He has
nerve and he has knowledge. Palmer and Pritchard
were among the heads of their profession. This man
strikes even deeper, but I think, Watson, that we shall
be able to strike deeper still. But we shall have horrors
enough before the night is over; for goodness’ sake
let us have a quiet pipe and turn our minds for a few
hours to something more cheerful.”
About nine o’clock the light among the trees was
extinguished, and all was dark in the direction of the
Manor House. Two hours passed slowly away, and
then, suddenly, just at the stroke of eleven, a single
bright light shone out right in front of us.
“That is our signal,” said Holmes, springing to his
feet; “it comes from the middle window.”

======================================================================
Rank 10 | Page 236 | TF-IDF Score: 0.1181
The Adventure of the Engineer’s Thumb
“ ‘We have judged it best that you should come
late. It is to recompense you for any inconvenience
that we are paying to you, a young and unknown
man, a fee which would buy an opinion from the
very heads of your profession. Still, of course, if you
would like to draw out of the business, there is plenty
of time to do so.’
“I thought of the ﬁfty guineas, and of how very
useful they would be to me. ‘Not at all,’ said I, ‘I
shall be very happy to accommodate myself to your
wishes. I should like, however, to understand a little
more clearly what it is that you wish me to do.’
“ ‘Quite so. It is very natural that the pledge of
secrecy which we have exacted from you should have
aroused your curiosity. I have no wish to commit
you to anything without your having it all laid be-
fore you. I suppose that we are absolutely safe from
eavesdroppers?’
“ ‘Entirely.’
“ ‘Then the matter stands thus. You are probably

In [45]:
def hybrid_retrieve_filtered(query, top_k=5, candidate_k=20):
    semantic_results = retrieve_documents(query, top_k=candidate_k)
    keyword_results = keyword_retrieve_filtered(query, top_k=candidate_k)

    # Remove very short chunks from semantic results
    semantic_results = [
        result
        for result in semantic_results
        if is_useful_chunk(result["text"])
    ]

    scores = {}
    chunk_data = {}

    # Semantic ranking
    for rank, result in enumerate(semantic_results, start=1):
        key = (
            result["page_number"],
            result["chunk_index"]
        )

        scores[key] = scores.get(key, 0) + 1 / (60 + rank)
        chunk_data[key] = result

    # Keyword ranking
    for rank, result in enumerate(keyword_results, start=1):
        key = (
            result["page_number"],
            result["chunk_index"]
        )

        scores[key] = scores.get(key, 0) + 1 / (60 + rank)
        chunk_data[key] = result

    # Sort by combined score
    ranked_keys = sorted(
        scores,
        key=scores.get,
        reverse=True
    )

    results = []

    for key in ranked_keys[:top_k]:
        result = chunk_data[key].copy()
        result["hybrid_score"] = scores[key]
        results.append(result)

    return results

In [46]:
question = "What is Sherlock Holmes's profession?"

hybrid_results = hybrid_retrieve_filtered(
    question,
    top_k=10,
    candidate_k=20
)

for i, chunk in enumerate(hybrid_results, start=1):
    print(f"\n{'=' * 70}")
    print(
        f"Rank {i} | Page {chunk['page_number']} "
        f"| Hybrid Score: {chunk['hybrid_score']:.4f}"
    )
    print(chunk["text"])

======================================================================
Rank 1 | Page 745 | Hybrid Score: 0.0164
Preface
Preface
The friends of Mr. Sherlock Holmes will be glad to learn that he is still alive and well, though
somewhat crippled by occasional attacks of rheumatism. He has, for many years, lived in a small
farm upon the downs ﬁve miles from Eastbourne, where his time is divided between philosophy
and agriculture. During this period of rest he has refused the most princely offers to take up
various cases, having determined that his retirement was a permanent one. The approach of the
German war caused him, however, to lay his remarkable combination of intellectual and practical
activity at the disposal of the government, with historical results which are recounted in His Last
Bow. Several previous experiences which have lain long in my portfolio have been added to His
Last Bow so as to complete the volume.
John H. Watson, M. D.
739

======================================================================
Rank 2 | Page 150 | Hybrid Score: 0.0164
turn, we never know where to ﬁnd the man himself.
He’ll crack a crib in Scotland one week, and be raising
money to build an orphanage in Cornwall the next.
I’ve been on his track for years and have never set
eyes on him yet.”
“I hope that I may have the pleasure of introduc-
ing you to-night. I’ve had one or two little turns also
with Mr. John Clay, and I agree with you that he is at
the head of his profession. It is past ten, however, and
quite time that we started. If you two will take the
ﬁrst hansom, Watson and I will follow in the second.”
Sherlock Holmes was not very communicative dur-
ing the long drive and lay back in the cab humming
the tunes which he had heard in the afternoon. We
rattled through an endless labyrinth of gas-lit streets
until we emerged into Farrington Street.
“We are close there now,” my friend remarked.
“This fellow Merryweather is a bank director, and
personally interested in the matter. I thought it as

======================================================================
Rank 3 | Page 855 | Hybrid Score: 0.0161
Preface
Preface
I fear that Mr. Sherlock Holmes may become like one of those popular tenors who, having
outlived their time, are still tempted to make repeated farewell bows to their indulgent audiences.
This must cease and he must go the way of all ﬂesh, material or imaginary. One likes to think that
there is some fantastic limbo for the children of imagination, some strange, impossible place where
the beaux of Fielding may still make love to the belles of Richardson, where Scott’s heroes still may
strut, Dickens’s delightful Cockneys still raise a laugh, and Thackeray’s worldlings continue to
carry on their reprehensible careers. Perhaps in some humble corner of such a Valhalla, Sherlock
and his Watson may for a time ﬁnd a place, while some more astute sleuth with some even less
astute comrade may ﬁll the stage which they have vacated.
His career has been a long one—though it is possible to exaggerate it; decrepit gentlemen who

======================================================================
Rank 4 | Page 554 | Hybrid Score: 0.0161
The Adventure of the Missing Three-Quarter
looked up with no very pleased expression upon his
dour features.
“I have heard your name, Mr. Sherlock Holmes,
and I am aware of your profession, one of which I by
no means approve.”
“In that, doctor, you will ﬁnd yourself in agree-
ment with every criminal in the country,” said my
friend, quietly.
“So far as your efforts are directed towards the
suppression of crime, sir, they must have the sup-
port of every reasonable member of the community,
though I cannot doubt that the ofﬁcial machinery is
amply sufﬁcient for the purpose. Where your calling
is more open to criticism is when you pry into the
secrets of private individuals, when you rake up fam-
ily matters which are better hidden, and when you
incidentally waste the time of men who are more busy
than yourself. At the present moment, for example,
I should be writing a treatise instead of conversing
with you.”
“No doubt, doctor; and yet the conversation may

======================================================================
Rank 5 | Page 234 | Hybrid Score: 0.0159
to Baker Street.
Sherlock Holmes was, as I expected, lounging
about his sitting-room in his dressing-gown, read-
ing the agony column of The Times and smoking his
before-breakfast pipe, which was composed of all the
plugs and dottles left from his smokes of the day be-
fore, all carefully dried and collected on the corner of
the mantelpiece. He received us in his quietly genial
fashion, ordered fresh rashers and eggs, and joined
us in a hearty meal. When it was concluded he set-
tled our new acquaintance upon the sofa, placed a
pillow beneath his head, and laid a glass of brandy
and water within his reach.
“It is easy to see that your experience has been no
common one, Mr. Hatherley,” said he. “Pray, lie down
there and make yourself absolutely at home. Tell us
what you can, but stop when you are tired and keep
up your strength with a little stimulant.”
“Thank you,” said my patient. “but I have felt an-
other man since the doctor bandaged me, and I think

======================================================================
Rank 6 | Page 20 | Hybrid Score: 0.0159
A Study In Scarlet
Sherlock Holmes sniffed sardonically. “Lecoq was
a miserable bungler,” he said, in an angry voice; “he
had only one thing to recommend him, and that was
his energy. That book made me positively ill. The
question was how to identify an unknown prisoner. I
could have done it in twenty-four hours. Lecoq took
six months or so. It might be made a text-book for
detectives to teach them what to avoid.”
I felt rather indignant at having two characters
whom I had admired treated in this cavalier style. I
walked over to the window, and stood looking out
into the busy street. “This fellow may be very clever,”
I said to myself, “but he is certainly very conceited.”
“There are no crimes and no criminals in these
days,” he said, querulously. “What is the use of hav-
ing brains in our profession? I know well that I have
it in me to make my name famous. No man lives or
has ever lived who has brought the same amount of
study and of natural talent to the detection of crime

======================================================================
Rank 7 | Page 143 | Hybrid Score: 0.0156
of extreme chagrin and discontent upon his features.
Sherlock Holmes’ quick eye took in my occupa-
tion, and he shook his head with a smile as he noticed
my questioning glances. “Beyond the obvious facts
that he has at some time done manual labour, that he
takes snuff, that he is a Freemason, that he has been
in China, and that he has done a considerable amount
of writing lately, I can deduce nothing else.”
Mr. Jabez Wilson started up in his chair, with his
foreﬁnger upon the paper, but his eyes upon my com-
panion.
“How, in the name of good-fortune, did you know
all that, Mr. Holmes?” he asked. “How did you know,
for example, that I did manual labour. It’s as true as
gospel, for I began as a ship’s carpenter.”
137

======================================================================
Rank 8 | Page 698 | Hybrid Score: 0.0156
started at once.”
We passed along the outer bounds of the Manor
House park until we came to a place where there was
a gap in the rails which fenced it. Through this we
slipped, and then in the gathering gloom we followed
Holmes until we had reached a shrubbery which lies
nearly opposite to the main door and the drawbridge.
The latter had not been raised. Holmes crouched
down behind the screen of laurels, and we all three
followed his example.
“Well, what are we to do now?” asked MacDonald
with some gruffness.
“Possess our souls in patience and make as little
noise as possible,” Holmes answered.
“What are we here for at all? I really think that
you might treat us with more frankness.”
Holmes laughed. “Watson insists that I am the
dramatist in real life,” said he. “Some touch of the
artist wells up within me, and calls insistently for a
well-staged performance. Surely our profession, Mr.
Mac, would be a drab and sordid one if we did not

======================================================================
Rank 9 | Page 200 | Hybrid Score: 0.0154
points about which I wished to be absolutely clear.
We shall now have a little supper and then retire, for
we may have a very busy day to-morrow.”
A large and comfortable double-bedded room had
been placed at our disposal, and I was quickly be-
tween the sheets, for I was weary after my night of
adventure. Sherlock Holmes was a man, however,
who, when he had an unsolved problem upon his
mind, would go for days, and even for a week, with-
out rest, turning it over, rearranging his facts, looking
at it from every point of view until he had either
fathomed it or convinced himself that his data were
insufﬁcient. It was soon evident to me that he was
now preparing for an all-night sitting. He took off
his coat and waistcoat, put on a large blue dressing-
gown, and then wandered about the room collecting
pillows from his bed and cushions from the sofa and
armchairs. With these he constructed a sort of Eastern
divan, upon which he perched himself cross-legged,

======================================================================
Rank 10 | Page 150 | Hybrid Score: 0.0154
the stranger with deference. “Still, I confess that I
miss my rubber. It is the ﬁrst Saturday night for
seven-and-twenty years that I have not had my rub-
ber.”
“I think you will ﬁnd,” said Sherlock Holmes,
“that you will play for a higher stake to-night than
you have ever done yet, and that the play will be more
exciting. For you, Mr. Merryweather, the stake will be
some £30,000; and for you, Jones, it will be the man
upon whom you wish to lay your hands.”
“John Clay, the murderer, thief, smasher, and
forger. He’s a young man, Mr. Merryweather, but
he is at the head of his profession, and I would rather
have my bracelets on him than on any criminal in
London. He’s a remarkable man, is young John Clay.
His grandfather was a royal duke, and he himself has
been to Eton and Oxford. His brain is as cunning as
his ﬁngers, and though we meet signs of him at every
turn, we never know where to ﬁnd the man himself.
He’ll crack a crib in Scotland one week, and be raising

In [47]:
import numpy as np

def weighted_hybrid_retrieve(query, top_k=5, candidate_k=20):
    # Get candidates from both retrievers
    semantic_results = retrieve_documents(query, top_k=candidate_k)
    keyword_results = keyword_retrieve_filtered(query, top_k=candidate_k)

    # Store candidates by page + chunk
    candidates = {}

    for result in semantic_results:
        key = (
            result["page_number"],
            result["chunk_index"]
        )

        if is_useful_chunk(result["text"]):
            candidates[key] = {
                "text": result["text"],
                "page_number": result["page_number"],
                "chunk_index": result["chunk_index"],
                "source": result["source"],
                "semantic_score": 1 - result["distance"],
                "keyword_score": 0.0
            }

    for result in keyword_results:
        key = (
            result["page_number"],
            result["chunk_index"]
        )

        if key not in candidates:
            candidates[key] = {
                "text": result["text"],
                "page_number": result["page_number"],
                "chunk_index": result["chunk_index"],
                "source": result["source"],
                "semantic_score": 0.0,
                "keyword_score": result["score"]
            }
        else:
            candidates[key]["keyword_score"] = result["score"]

    # Convert candidates to list
    results = list(candidates.values())

    # Normalize scores
    semantic_scores = np.array(
        [r["semantic_score"] for r in results]
    )

    keyword_scores = np.array(
        [r["keyword_score"] for r in results]
    )

    def min_max_normalize(scores):
        min_score = scores.min()
        max_score = scores.max()

        if max_score == min_score:
            return np.zeros_like(scores)

        return (scores - min_score) / (max_score - min_score)

    semantic_normalized = min_max_normalize(semantic_scores)
    keyword_normalized = min_max_normalize(keyword_scores)

    # Weighted combination
    for i, result in enumerate(results):
        result["hybrid_score"] = (
            0.4 * semantic_normalized[i]
            + 0.6 * keyword_normalized[i]
        )

    # Sort by final score
    results.sort(
        key=lambda x: x["hybrid_score"],
        reverse=True
    )

    return results[:top_k]

In [48]:
question = "What is Sherlock Holmes's profession?"

weighted_results = weighted_hybrid_retrieve(
    question,
    top_k=10,
    candidate_k=20
)

for i, chunk in enumerate(weighted_results, start=1):
    print(f"\n{'=' * 70}")
    print(
        f"Rank {i} | Page {chunk['page_number']} "
        f"| Hybrid Score: {chunk['hybrid_score']:.4f}"
    )
    print(chunk["text"])

======================================================================
Rank 1 | Page 150 | Hybrid Score: 0.6000
turn, we never know where to ﬁnd the man himself.
He’ll crack a crib in Scotland one week, and be raising
money to build an orphanage in Cornwall the next.
I’ve been on his track for years and have never set
eyes on him yet.”
“I hope that I may have the pleasure of introduc-
ing you to-night. I’ve had one or two little turns also
with Mr. John Clay, and I agree with you that he is at
the head of his profession. It is past ten, however, and
quite time that we started. If you two will take the
ﬁrst hansom, Watson and I will follow in the second.”
Sherlock Holmes was not very communicative dur-
ing the long drive and lay back in the cab humming
the tunes which he had heard in the afternoon. We
rattled through an endless labyrinth of gas-lit streets
until we emerged into Farrington Street.
“We are close there now,” my friend remarked.
“This fellow Merryweather is a bank director, and
personally interested in the matter. I thought it as

======================================================================
Rank 2 | Page 554 | Hybrid Score: 0.5812
The Adventure of the Missing Three-Quarter
looked up with no very pleased expression upon his
dour features.
“I have heard your name, Mr. Sherlock Holmes,
and I am aware of your profession, one of which I by
no means approve.”
“In that, doctor, you will ﬁnd yourself in agree-
ment with every criminal in the country,” said my
friend, quietly.
“So far as your efforts are directed towards the
suppression of crime, sir, they must have the sup-
port of every reasonable member of the community,
though I cannot doubt that the ofﬁcial machinery is
amply sufﬁcient for the purpose. Where your calling
is more open to criticism is when you pry into the
secrets of private individuals, when you rake up fam-
ily matters which are better hidden, and when you
incidentally waste the time of men who are more busy
than yourself. At the present moment, for example,
I should be writing a treatise instead of conversing
with you.”
“No doubt, doctor; and yet the conversation may

======================================================================
Rank 3 | Page 20 | Hybrid Score: 0.5495
A Study In Scarlet
Sherlock Holmes sniffed sardonically. “Lecoq was
a miserable bungler,” he said, in an angry voice; “he
had only one thing to recommend him, and that was
his energy. That book made me positively ill. The
question was how to identify an unknown prisoner. I
could have done it in twenty-four hours. Lecoq took
six months or so. It might be made a text-book for
detectives to teach them what to avoid.”
I felt rather indignant at having two characters
whom I had admired treated in this cavalier style. I
walked over to the window, and stood looking out
into the busy street. “This fellow may be very clever,”
I said to myself, “but he is certainly very conceited.”
“There are no crimes and no criminals in these
days,” he said, querulously. “What is the use of hav-
ing brains in our profession? I know well that I have
it in me to make my name famous. No man lives or
has ever lived who has brought the same amount of
study and of natural talent to the detection of crime

======================================================================
Rank 4 | Page 698 | Hybrid Score: 0.5493
started at once.”
We passed along the outer bounds of the Manor
House park until we came to a place where there was
a gap in the rails which fenced it. Through this we
slipped, and then in the gathering gloom we followed
Holmes until we had reached a shrubbery which lies
nearly opposite to the main door and the drawbridge.
The latter had not been raised. Holmes crouched
down behind the screen of laurels, and we all three
followed his example.
“Well, what are we to do now?” asked MacDonald
with some gruffness.
“Possess our souls in patience and make as little
noise as possible,” Holmes answered.
“What are we here for at all? I really think that
you might treat us with more frankness.”
Holmes laughed. “Watson insists that I am the
dramatist in real life,” said he. “Some touch of the
artist wells up within me, and calls insistently for a
well-staged performance. Surely our profession, Mr.
Mac, would be a drab and sordid one if we did not

======================================================================
Rank 5 | Page 150 | Hybrid Score: 0.5440
the stranger with deference. “Still, I confess that I
miss my rubber. It is the ﬁrst Saturday night for
seven-and-twenty years that I have not had my rub-
ber.”
“I think you will ﬁnd,” said Sherlock Holmes,
“that you will play for a higher stake to-night than
you have ever done yet, and that the play will be more
exciting. For you, Mr. Merryweather, the stake will be
some £30,000; and for you, Jones, it will be the man
upon whom you wish to lay your hands.”
“John Clay, the murderer, thief, smasher, and
forger. He’s a young man, Mr. Merryweather, but
he is at the head of his profession, and I would rather
have my bracelets on him than on any criminal in
London. He’s a remarkable man, is young John Clay.
His grandfather was a royal duke, and he himself has
been to Eton and Oxford. His brain is as cunning as
his ﬁngers, and though we meet signs of him at every
turn, we never know where to ﬁnd the man himself.
He’ll crack a crib in Scotland one week, and be raising

======================================================================
Rank 6 | Page 324 | Hybrid Score: 0.5061
son and I were. His attack did not last long, however,
for when we undid his collar, and sprinkled the water
from one of the ﬁnger-glasses over his face, he gave a
gasp or two and sat up.
“ ‘Ah, boys,’ said he, forcing a smile, ‘I hope I
haven’t frightened you. Strong as I look, there is a
weak place in my heart, and it does not take much to
knock me over. I don’t know how you manage this,
Mr. Holmes, but it seems to me that all the detectives
of fact and of fancy would be children in your hands.
That’s your line of life, sir, and you may take the word
of a man who has seen something of the world.’
“And that recommendation, with the exaggerated
estimate of my ability with which he prefaced it, was,
if you will believe me, Watson, the very ﬁrst thing
which ever made me feel that a profession might be
made out of what had up to that time been the mer-
est hobby. At the moment, however, I was too much
concerned at the sudden illness of my host to think
of anything else.

======================================================================
Rank 7 | Page 380 | Hybrid Score: 0.4882
the way into the hall. Through the glass paneling
I caught a glimpse of a large and luxurious room,
in which a considerable number of men were sit-
ting about and reading papers, each in his own little
nook. Holmes showed me into a small chamber which
looked out into Pall Mall, and then, leaving me for
a minute, he came back with a companion whom I
knew could only be his brother.
Mycroft Holmes was a much larger and stouter
man than Sherlock. His body was absolutely cor-
pulent, but his face, though massive, had preserved
something of the sharpness of expression which was
so remarkable in that of his brother. His eyes, which
were of a peculiarly light, watery gray, seemed to al-
ways retain that far-away, introspective look which I
had only observed in Sherlock’s when he was exerting
his full powers.
“I am glad to meet you, sir,” said he, putting out
a broad, fat hand like the ﬂipper of a seal. “I hear of
Sherlock everywhere since you became his chronicler.

======================================================================
Rank 8 | Page 459 | Hybrid Score: 0.4769
to me, and she would have married me, I believe, if
I had taken over another profession; but she would
have nothing to do with anything on the cross. It was
only after her marriage to this Englishman that I was
able to ﬁnd out where she was. I wrote to her, but
got no answer. After that I came over, and, as letters
were no use, I put my messages where she could read
them.
“Well, I have been here a month now. I lived in
that farm, where I had a room down below, and could
get in and out every night, and no one the wiser. I
tried all I could to coax Elsie away. I knew that she
read the messages, for once she wrote an answer un-
der one of them. Then my temper got the better of me,
and I began to threaten her. She sent me a letter then,
imploring me to go away and saying that it would
break her heart if any scandal should come upon her
husband. She said that she would come down when
her husband was asleep at three in the morning, and
speak with me through the end window, if I would

======================================================================
Rank 9 | Page 228 | Hybrid Score: 0.4718
The Adventure of the Speckled Band
“Holmes,” I cried, “I seem to see dimly what you
are hinting at. We are only just in time to prevent
some subtle and horrible crime.”
“Subtle enough and horrible enough. When a doc-
tor does go wrong he is the ﬁrst of criminals. He has
nerve and he has knowledge. Palmer and Pritchard
were among the heads of their profession. This man
strikes even deeper, but I think, Watson, that we shall
be able to strike deeper still. But we shall have horrors
enough before the night is over; for goodness’ sake
let us have a quiet pipe and turn our minds for a few
hours to something more cheerful.”
About nine o’clock the light among the trees was
extinguished, and all was dark in the direction of the
Manor House. Two hours passed slowly away, and
then, suddenly, just at the stroke of eleven, a single
bright light shone out right in front of us.
“That is our signal,” said Holmes, springing to his
feet; “it comes from the middle window.”

======================================================================
Rank 10 | Page 236 | Hybrid Score: 0.4625
The Adventure of the Engineer’s Thumb
“ ‘We have judged it best that you should come
late. It is to recompense you for any inconvenience
that we are paying to you, a young and unknown
man, a fee which would buy an opinion from the
very heads of your profession. Still, of course, if you
would like to draw out of the business, there is plenty
of time to do so.’
“I thought of the ﬁfty guineas, and of how very
useful they would be to me. ‘Not at all,’ said I, ‘I
shall be very happy to accommodate myself to your
wishes. I should like, however, to understand a little
more clearly what it is that you wish me to do.’
“ ‘Quite so. It is very natural that the pledge of
secrecy which we have exacted from you should have
aroused your curiosity. I have no wish to commit
you to anything without your having it all laid be-
fore you. I suppose that we are absolutely safe from
eavesdroppers?’
“ ‘Entirely.’
“ ‘Then the matter stands thus. You are probably

### Retrieval Improvement

The initial semantic retrieval did not always return the most relevant chunks for questions containing specific terms such as "profession".

To improve retrieval, a hybrid approach was tested by combining semantic similarity with TF-IDF keyword matching.

Short and low-information chunks were also filtered out before keyword retrieval. This reduced noise from title-only or very short chunks and improved the ranking of relevant textual evidence.

For the question "What is Sherlock Holmes's profession?", the hybrid retriever successfully retrieved relevant passages, including passages on pages 554, 324, and 20 that explicitly discuss Holmes's profession, calling, and detective work.

The hybrid approach will therefore be used as the final retrieval strategy for the RAG pipeline.

In [49]:
def ask_rag(question, top_k=5):
    retrieved_chunks = hybrid_retrieve_filtered(
        question,
        top_k=top_k
    )

    prompt = build_prompt(question, retrieved_chunks)

    response = chat(
        model="qwen3:1.7b",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    answer = response["message"]["content"]

    return answer, retrieved_chunks

In [50]:
answer, sources = ask_rag(
    "What is Sherlock Holmes's profession?"
)

print(answer)

print("\nRetrieved Sources:")
for source in sources:
    print(
        f"- Page {source['page_number']} "
        f"(hybrid score: {source['hybrid_score']:.4f})"
    )

The context indicates that Sherlock Holmes is a **detective** based on the preface in Source 1 (Page 745), which states he has "refused the most princely offers to take up various cases, having determined that his retirement was a permanent one." While the preface mentions his retirement and pursuits in philosophy and agriculture, the explicit mention of his profession as a **detective** is derived from the story's context (Source 2, Page 150), where he is described as a figure who has been on Watson's track but never set eyes on him.

**Answer:**
Sherlock Holmes's profession is a **detective**, as indicated in the preface (Source 1) and the story's context (Source 2).

Retrieved Sources:
- Page 745 (hybrid score: 0.0164)
- Page 150 (hybrid score: 0.0164)
- Page 855 (hybrid score: 0.0161)
- Page 554 (hybrid score: 0.0161)
- Page 234 (hybrid score: 0.0159)

### Retrieval and Generation Result

The hybrid retrieval strategy improved the retrieval of relevant evidence for the question about Sherlock Holmes's profession.

The retrieved context included passages that explicitly refer to Holmes's profession, calling, and detective work. The generated answer correctly identified Sherlock Holmes as a detective.

However, the generated response also included an interpretation that was not directly supported by every cited page. This demonstrates that retrieval quality and citation grounding should both be considered during evaluation.

Overall, the hybrid retriever provided sufficiently relevant context for the RAG system and will be used for the final evaluation.

## 2.7 Export

The Chroma vector store has been persisted to disk so that the embeddings do not need to be regenerated when the application starts.

The RAG configuration is also exported to a JSON file. This configuration records the chunking parameters, embedding model, vector store, and retrieval strategy used to build the system.

In [51]:
import json

config = {
    "chunk_size": 1000,
    "chunk_overlap": 150,
    "embedding_model": "all-MiniLM-L6-v2",
    "vector_store": "ChromaDB",
    "collection_name": "sherlock_holmes",
    "retrieval_strategy": "hybrid",
    "semantic_weight": 0.4,
    "keyword_weight": 0.6,
    "top_k": 5
}

CONFIG_PATH = PROJECT_ROOT / "data" / "rag_config.json"

with open(CONFIG_PATH, "w", encoding="utf-8") as f:
    json.dump(config, f, indent=4)

print("Configuration saved to:")
print(CONFIG_PATH)

Configuration saved to:
C:\Users\New\OneDrive - Faculty Of Science (Ain Shams University)\RAG_Assistant_Project\data\rag_config.json

In [52]:
print("Vector store exists:", VECTOR_STORE_PATH.exists())
print("Vector store path:", VECTOR_STORE_PATH)

print("\nConfiguration exists:", CONFIG_PATH.exists())
print("Configuration path:", CONFIG_PATH)

Vector store exists: True
Vector store path: C:\Users\New\OneDrive - Faculty Of Science (Ain Shams University)\RAG_Assistant_Project\data\vector_store

Configuration exists: True
Configuration path: C:\Users\New\OneDrive - Faculty Of Science (Ain Shams University)\RAG_Assistant_Project\data\rag_config.json